"""售后完善

Revision ID: 01528670f7ad
Revises: 9d2d9a2f9bb3
Create Date: 2018-11-21 13:49:30.904724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01528670f7ad'
down_revision = '9d2d9a2f9bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderRefund', sa.Column('ORlogisticCompany', sa.String(length=32), nullable=True))
    op.add_column('OrderRefund', sa.Column('ORlogisticData', sa.Text(), nullable=True))
    op.add_column('OrderRefund', sa.Column('ORlogisticLostResult', sa.Text(), nullable=True))
    op.add_column('OrderRefund', sa.Column('ORlogisticSignStatus', sa.Integer(), nullable=True))
    op.add_column('OrderRefund', sa.Column('ORstatus', sa.Integer(), nullable=True))
    op.add_column('OrderRefundApply', sa.Column('ORAcheckUser', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderRefundApply', 'ORAcheckUser')
    op.drop_column('OrderRefund', 'ORstatus')
    op.drop_column('OrderRefund', 'ORlogisticSignStatus')
    op.drop_column('OrderRefund', 'ORlogisticLostResult')
    op.drop_column('OrderRefund', 'ORlogisticData')
    op.drop_column('OrderRefund', 'ORlogisticCompany')
    # ### end Alembic commands ###
