"""news_update_part

Revision ID: 01ba748a96b0
Revises: 1a58515010bd
Create Date: 2019-04-26 01:01:21.616134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01ba748a96b0'
down_revision = '1a58515010bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NewsCategory')
    op.drop_column('News', 'NSCid')
    op.add_column('TopicConversation', sa.Column('TOCfrom', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TopicConversation', 'TOCfrom')
    op.add_column('News', sa.Column('NSCid', mysql.VARCHAR(length=64), nullable=True))
    op.create_table('NewsCategory',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('NSCid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('NSCcreate', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('NSCname', mysql.TEXT(), nullable=True),
    sa.Column('NSCsort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('NSCid'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
