"""index fix

Revision ID: 01bfbbb340b2
Revises: 525c1879e9c7
Create Date: 2018-11-12 13:30:19.771235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01bfbbb340b2'
down_revision = '525c1879e9c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IndexBanner', sa.Column('IBshow', sa.Boolean(), nullable=True))
    op.drop_column('IndexBrand', 'IBshow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IndexBrand', sa.Column('IBshow', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('IndexBanner', 'IBshow')
    # ### end Alembic commands ###
