"""'add'

Revision ID: 039440f58f61
Revises: fcb2369df4d5
Create Date: 2018-11-24 05:53:09.388288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039440f58f61'
down_revision = 'fcb2369df4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Admin', sa.Column('ADtelphone', sa.String(length=13), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Admin', 'ADtelphone')
    # ### end Alembic commands ###
