"""新人商品描述

Revision ID: 06496384940f
Revises: e922800747e2
Create Date: 2018-12-07 10:13:59.542374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06496384940f'
down_revision = 'e922800747e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FreshManFirstProduct', sa.Column('PRdescription', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FreshManFirstProduct', 'PRdescription')
    # ### end Alembic commands ###
