"""add

Revision ID: 07873d2d8c2b
Revises: fce77a241d2f
Create Date: 2019-04-27 22:08:58.159626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07873d2d8c2b'
down_revision = 'fce77a241d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CouponCode',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('CCid', sa.String(length=64), nullable=False),
    sa.Column('COid', sa.String(length=64), nullable=False),
    sa.Column('CCcode', sa.String(length=12), nullable=True),
    sa.Column('CCused', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('CCid')
    )
    op.create_table('Entry',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ENid', sa.String(length=64), nullable=False),
    sa.Column('ENpic', sa.Text(), nullable=True),
    sa.Column('ENshow', sa.Boolean(), nullable=True),
    sa.Column('contentlink', mysql.LONGTEXT(), nullable=True),
    sa.Column('ENtype', sa.Integer(), nullable=True),
    sa.Column('ACid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ENid')
    )
    op.create_table('HypermarketIndexBanner',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('HIBid', sa.String(length=64), nullable=False),
    sa.Column('HIBpic', sa.String(length=255), nullable=False),
    sa.Column('HIBsort', sa.Integer(), nullable=True),
    sa.Column('HIBshow', sa.Boolean(), nullable=True),
    sa.Column('contentlink', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('HIBid')
    )
    op.create_table('IntegralProduct',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('IPid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=False),
    sa.Column('IPfrom', sa.Integer(), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=True),
    sa.Column('IPrejectReason', sa.String(length=255), nullable=True),
    sa.Column('IPstatus', sa.Integer(), nullable=True),
    sa.Column('IPprice', sa.BIGINT(), nullable=True),
    sa.Column('IPsaleVolume', sa.BIGINT(), nullable=True),
    sa.Column('IPaverageScore', sa.Float(precision=10), nullable=True),
    sa.PrimaryKeyConstraint('IPid')
    )
    op.create_table('IntegralProductSku',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('IPSid', sa.String(length=64), nullable=False),
    sa.Column('IPid', sa.String(length=64), nullable=False),
    sa.Column('IPSstock', sa.BIGINT(), nullable=True),
    sa.Column('SKUid', sa.String(length=64), nullable=True),
    sa.Column('SKUprice', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('IPSid')
    )
    op.create_table('TopicConversation',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('TOCid', sa.String(length=64), nullable=False),
    sa.Column('TOCcreate', sa.String(length=64), nullable=True),
    sa.Column('TOCtitle', sa.Text(), nullable=True),
    sa.Column('TOCfrom', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('TOCid')
    )
    op.create_table('UserLocation',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ULid', sa.String(length=64), nullable=False),
    sa.Column('ULformattedAddress', sa.Text(), nullable=True),
    sa.Column('ULcountry', sa.Text(), nullable=True),
    sa.Column('ULprovince', sa.Text(), nullable=True),
    sa.Column('ULcity', sa.Text(), nullable=True),
    sa.Column('ULdistrict', sa.Text(), nullable=True),
    sa.Column('ULresult', sa.Text(), nullable=True),
    sa.Column('ULlng', sa.Text(), nullable=True),
    sa.Column('ULlat', sa.Text(), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ULid')
    )
    op.add_column('Coupon', sa.Column('COcode', sa.Integer(), nullable=True))
    op.add_column('News', sa.Column('NElocation', sa.Text(), nullable=True))
    op.add_column('News', sa.Column('TOCid', sa.String(length=64), nullable=True))
    op.add_column('OrderMain', sa.Column('OMintegralpayed', sa.Integer(), nullable=True))
    op.add_column('ProductBrand', sa.Column('PBintegralPayRate', sa.Integer(), nullable=True))
    op.add_column('Supplizer', sa.Column('SUgrade', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('USgrade', sa.Integer(), nullable=True))
    op.add_column('UserActivationCode', sa.Column('ACAid', sa.String(length=64), nullable=True))
    op.add_column('UserSignIn', sa.Column('OPayno', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserSignIn', 'OPayno')
    op.drop_column('UserActivationCode', 'ACAid')
    op.drop_column('User', 'USgrade')
    op.drop_column('Supplizer', 'SUgrade')
    op.drop_column('ProductBrand', 'PBintegralPayRate')
    op.drop_column('OrderMain', 'OMintegralpayed')
    op.drop_column('News', 'TOCid')
    op.drop_column('News', 'NElocation')
    op.drop_column('Coupon', 'COcode')
    op.drop_table('UserLocation')
    op.drop_table('TopicConversation')
    op.drop_table('IntegralProductSku')
    op.drop_table('IntegralProduct')
    op.drop_table('HypermarketIndexBanner')
    op.drop_table('Entry')
    op.drop_table('CouponCode')
    # ### end Alembic commands ###
