"""'add'

Revision ID: 078caa9902de
Revises: ab2ee1ae6140
Create Date: 2018-11-14 03:43:24.552948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078caa9902de'
down_revision = 'ab2ee1ae6140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AdminNotes', sa.Column('ANaction', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AdminNotes', 'ANaction')
    # ### end Alembic commands ###
