"""供应商字段

Revision ID: 09104d72b2e5
Revises: f52fe47267e8
Create Date: 2018-12-14 17:43:59.960122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09104d72b2e5'
down_revision = 'f52fe47267e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Supplizer', sa.Column('SUloginPhone', sa.String(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Supplizer', 'SUloginPhone')
    # ### end Alembic commands ###
