"""'news_comment_add_NCrootid'

Revision ID: 0c1c21e7a42a
Revises: 64c2674daf14
Create Date: 2018-11-15 20:19:27.441939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1c21e7a42a'
down_revision = '64c2674daf14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NewsCommentFavorite',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('NCFid', sa.String(length=64), nullable=False),
    sa.Column('NCid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('NCFid')
    )
    op.add_column('NewsComment', sa.Column('NCrootid', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NewsComment', 'NCrootid')
    op.drop_table('NewsCommentFavorite')
    # ### end Alembic commands ###
