"""'fix'

Revision ID: 11baa3b41e64
Revises: dd69e5d45ee7
Create Date: 2019-01-09 05:11:09.402775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11baa3b41e64'
down_revision = 'dd69e5d45ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('UStoAgentTime', sa.DateTime(), nullable=True))
    op.add_column('UserSalesvolume', sa.Column('USVamountagent', sa.DECIMAL(precision=28, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserSalesvolume', 'USVamountagent')
    op.drop_column('User', 'UStoAgentTime')
    # ### end Alembic commands ###
