"""modify_commodity

Revision ID: 163e60d386bc
Revises: 26c5575964ac
Create Date: 2018-11-28 13:35:01.630425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '163e60d386bc'
down_revision = '26c5575964ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('GuessNumAward', 'SKUprice',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.add_column('TrialCommodity', sa.Column('PBid', sa.String(length=64), nullable=True))
    op.add_column('TrialCommoditySku', sa.Column('SKUprice', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TrialCommoditySku', 'SKUprice')
    op.drop_column('TrialCommodity', 'PBid')
    op.alter_column('GuessNumAward', 'SKUprice',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
