"""'add'

Revision ID: 1a58515010bd
Revises: 85fc69dd43c5
Create Date: 2019-04-24 22:27:53.108336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a58515010bd'
down_revision = '85fc69dd43c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NewsCategory',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('NSCid', sa.String(length=64), nullable=False),
    sa.Column('NSCcreate', sa.String(length=64), nullable=True),
    sa.Column('NSCname', sa.Text(), nullable=True),
    sa.Column('NSCsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('NSCid')
    )
    op.create_table('TopicConversation',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('TOCid', sa.String(length=64), nullable=False),
    sa.Column('TOCcreate', sa.String(length=64), nullable=True),
    sa.Column('TOCtitle', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('TOCid')
    )
    op.create_table('UserLocation',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ULid', sa.String(length=64), nullable=False),
    sa.Column('ULformattedAddress', sa.Text(), nullable=True),
    sa.Column('ULcountry', sa.Text(), nullable=True),
    sa.Column('ULprovince', sa.Text(), nullable=True),
    sa.Column('ULcity', sa.Text(), nullable=True),
    sa.Column('ULdistrict', sa.Text(), nullable=True),
    sa.Column('ULresult', sa.Text(), nullable=True),
    sa.Column('ULlng', sa.Text(), nullable=True),
    sa.Column('ULlat', sa.Text(), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ULid')
    )
    op.create_table('UserNewsCategory',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UNC', sa.String(length=64), nullable=False),
    sa.Column('NSCid', sa.String(length=64), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('UNCsort', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('UNC')
    )
    op.add_column('News', sa.Column('NElocation', sa.Text(), nullable=True))
    op.add_column('News', sa.Column('NSCid', sa.String(length=64), nullable=True))
    op.add_column('News', sa.Column('TOCid', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('News', 'TOCid')
    op.drop_column('News', 'NSCid')
    op.drop_column('News', 'NElocation')
    op.drop_table('UserNewsCategory')
    op.drop_table('UserLocation')
    op.drop_table('TopicConversation')
    op.drop_table('NewsCategory')
    # ### end Alembic commands ###
