"""活动-订单

Revision ID: 1a901be3889b
Revises: 03b5e6076e08
Create Date: 2019-01-08 02:42:31.617722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a901be3889b'
down_revision = '03b5e6076e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MagicBoxFlow',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('MBFid', sa.String(length=64), nullable=False),
    sa.Column('OMid', sa.String(length=64), nullable=False),
    sa.Column('MBJid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('MBFid')
    )
    op.add_column('GuessAwardFlow', sa.Column('OMid', sa.String(length=64), nullable=True))
    op.add_column('GuessNum', sa.Column('GNAAid', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GuessNum', 'GNAAid')
    op.drop_column('GuessAwardFlow', 'OMid')
    op.drop_table('MagicBoxFlow')
    # ### end Alembic commands ###
