"""'add'

Revision ID: 1c027d2dd396
Revises: b626301225a8
Create Date: 2018-12-05 16:47:06.264898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c027d2dd396'
down_revision = 'b626301225a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Quest', sa.Column('QUstatus', sa.Integer(), nullable=True))
    op.add_column('QuestOutline', sa.Column('QOstatus', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('QuestOutline', 'QOstatus')
    op.drop_column('Quest', 'QUstatus')
    # ### end Alembic commands ###
