"""供应商手机字段

Revision ID: 1d8a7d1d164c
Revises: 09104d72b2e5
Create Date: 2018-12-14 18:13:37.809727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d8a7d1d164c'
down_revision = '09104d72b2e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Supplizer', 'SUlinkPhone',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.alter_column('Supplizer', 'SUloginPhone',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.create_index(op.f('ix_Supplizer_SUloginPhone'), 'Supplizer', ['SUloginPhone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Supplizer_SUloginPhone'), table_name='Supplizer')
    op.alter_column('Supplizer', 'SUloginPhone',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.alter_column('Supplizer', 'SUlinkPhone',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###
