"""tablename

Revision ID: 20b98987f641
Revises: 4845e31088d0
Create Date: 2018-11-26 12:44:31.489611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20b98987f641'
down_revision = '4845e31088d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GuessAwardFlow',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('GAFid', sa.String(length=64), nullable=False),
    sa.Column('GNid', sa.String(length=64), nullable=False),
    sa.Column('GAFstatus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('GAFid'),
    sa.UniqueConstraint('GNid')
    )
    op.drop_index('GNid', table_name='guess_award_flow')
    op.drop_table('guess_award_flow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guess_award_flow',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('GAFid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('GNid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('GAFstatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('GAFid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('GNid', 'guess_award_flow', ['GNid'], unique=True)
    op.drop_table('GuessAwardFlow')
    # ### end Alembic commands ###
