"""供应商1

Revision ID: 2424ef83299b
Revises: fa3e893cb5dd
Create Date: 2018-12-03 16:13:08.460013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2424ef83299b'
down_revision = 'fa3e893cb5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplizer')
    op.add_column('Supplizer', sa.Column('SUheader', sa.String(length=255), nullable=True))
    op.add_column('Supplizer', sa.Column('SUpassword', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Supplizer', 'SUpassword')
    op.drop_column('Supplizer', 'SUheader')
    op.create_table('supplizer',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('SUid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('SUname', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('SUlinkman', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('SUlinkPhone', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('SUaddress', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('SUstatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('SUid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
