"""售后类型

Revision ID: 25802cb07269
Revises: e0fc212867b0
Create Date: 2018-11-20 20:32:58.784290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25802cb07269'
down_revision = 'e0fc212867b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DisputeType', sa.Column('DItype', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DisputeType', 'DItype')
    # ### end Alembic commands ###
