"""规则加字段

Revision ID: 258a7a698576
Revises: 459be37c2041
Create Date: 2018-12-13 13:10:00.281323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258a7a698576'
down_revision = '459be37c2041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ActivationCodeRule', sa.Column('ACRisShow', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ActivationCodeRule', 'ACRisShow')
    # ### end Alembic commands ###
