"""add column 

Revision ID: 261fdf11108a
Revises: 407dd91aec9e
Create Date: 2018-11-06 00:01:41.000080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261fdf11108a'
down_revision = '407dd91aec9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('CreaterId', sa.String(length=64), nullable=False))
    op.add_column('Products', sa.Column('PRfrom', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'PRfrom')
    op.drop_column('Products', 'CreaterId')
    # ### end Alembic commands ###
