"""猜数字奖励设置

Revision ID: 26c5575964ac
Revises: f1e3cbd2fe31
Create Date: 2018-11-28 10:38:02.674840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c5575964ac'
down_revision = 'f1e3cbd2fe31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GuessNum', sa.Column('Price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GuessNum', 'Price')
    # ### end Alembic commands ###
