"""brand item

Revision ID: 28614b616429
Revises: 32d2f76eb122
Create Date: 2018-11-09 14:38:26.774248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28614b616429'
down_revision = '32d2f76eb122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BrandItems',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('BIid', sa.String(length=64), nullable=False),
    sa.Column('BIname', sa.String(length=16), nullable=False),
    sa.Column('BIsort', sa.Integer(), nullable=True),
    sa.Column('BIdesc', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('BIid')
    )
    op.create_table('BrandwithItems',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('BWIid', sa.String(length=64), nullable=False),
    sa.Column('BIid', sa.String(length=64), nullable=False),
    sa.Column('PBid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('BWIid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BrandwithItems')
    op.drop_table('BrandItems')
    # ### end Alembic commands ###
