"""commodity_skuvalue

Revision ID: 2903d42872f9
Revises: d36b852b6041
Create Date: 2018-12-11 19:05:18.758754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2903d42872f9'
down_revision = 'd36b852b6041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TrialCommoditySkuValue', sa.Column('TCid', sa.String(length=64), nullable=False))
    op.add_column('TrialCommoditySkuValue', sa.Column('TSKUvalue', sa.Text(), nullable=True))
    op.drop_column('TrialCommoditySkuValue', 'PSKUvalue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TrialCommoditySkuValue', sa.Column('PSKUvalue', mysql.TEXT(), nullable=True))
    op.drop_column('TrialCommoditySkuValue', 'TSKUvalue')
    op.drop_column('TrialCommoditySkuValue', 'TCid')
    # ### end Alembic commands ###
