"""fix

Revision ID: 2b7923d19eb6
Revises: c13345b8f1e9
Create Date: 2018-12-19 18:03:53.996044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7923d19eb6'
down_revision = 'c13345b8f1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
