"""'add'

Revision ID: 2db37d59cdec
Revises: aff0f00096e3
Create Date: 2019-04-10 00:50:20.256987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2db37d59cdec'
down_revision = 'aff0f00096e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TimeLimitedProduct', 'PRmainpic')
    op.drop_column('TimeLimitedProduct', 'PRattribute')
    op.drop_column('TimeLimitedProduct', 'PRdescription')
    op.drop_column('TimeLimitedProduct', 'PBname')
    op.drop_column('TimeLimitedProduct', 'PRtitle')
    op.drop_column('TimeLimitedProduct', 'PRfeight')
    op.drop_column('TimeLimitedProduct', 'PBid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TimeLimitedProduct', sa.Column('PBid', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('TimeLimitedProduct', sa.Column('PRfeight', mysql.FLOAT(), nullable=True))
    op.add_column('TimeLimitedProduct', sa.Column('PRtitle', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('TimeLimitedProduct', sa.Column('PBname', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('TimeLimitedProduct', sa.Column('PRdescription', mysql.TEXT(), nullable=True))
    op.add_column('TimeLimitedProduct', sa.Column('PRattribute', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('TimeLimitedProduct', sa.Column('PRmainpic', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
