"""change_banner_prid_to_link

Revision ID: 2e501f910972
Revises: 3921655d9519
Create Date: 2019-01-02 10:08:27.226837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e501f910972'
down_revision = '3921655d9519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IndexBanner', sa.Column('contentlink', sa.String(length=255), nullable=False))
    op.drop_column('IndexBanner', 'PRid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IndexBanner', sa.Column('PRid', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('IndexBanner', 'contentlink')
    # ### end Alembic commands ###
