"""品牌热卖

Revision ID: 2fa61d4d0a32
Revises: 49543bb8bdde
Create Date: 2018-11-12 12:23:56.974422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fa61d4d0a32'
down_revision = '49543bb8bdde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IndexBanner',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('IBid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('IBpic', sa.String(length=255), nullable=False),
    sa.Column('IBsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('IBid')
    )
    op.drop_column('OrderLogistics', 'OPid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderLogistics', sa.Column('OPid', mysql.VARCHAR(length=125), nullable=True))
    op.drop_table('IndexBanner')
    # ### end Alembic commands ###
