"""test

Revision ID: 307bf4cafc44
Revises: 911d3877424c
Create Date: 2018-11-02 12:33:56.384673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307bf4cafc44'
down_revision = '911d3877424c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
