"""活动申请加字段

Revision ID: 32112ca8af58
Revises: ec41d91cb048
Create Date: 2018-12-10 11:13:49.077736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32112ca8af58'
down_revision = 'ec41d91cb048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FreshManFirstApply', sa.Column('ADid', sa.String(length=64), nullable=True))
    op.add_column('FreshManFirstApply', sa.Column('FMFArejectReson', sa.String(length=255), nullable=True))
    op.add_column('GuessNumAward', sa.Column('ADid', sa.String(length=64), nullable=True))
    op.add_column('GuessNumAward', sa.Column('GNAArejectReason', sa.String(length=64), nullable=True))
    op.add_column('MagicBoxApply', sa.Column('ADid', sa.String(length=64), nullable=True))
    op.add_column('MagicBoxApply', sa.Column('MBArejectReason', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MagicBoxApply', 'MBArejectReason')
    op.drop_column('MagicBoxApply', 'ADid')
    op.drop_column('GuessNumAward', 'GNAArejectReason')
    op.drop_column('GuessNumAward', 'ADid')
    op.drop_column('FreshManFirstApply', 'FMFArejectReson')
    op.drop_column('FreshManFirstApply', 'ADid')
    # ### end Alembic commands ###
