"""'add'

Revision ID: 32d2f76eb122
Revises: 7844e2262761
Create Date: 2018-11-09 12:58:52.118320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d2f76eb122'
down_revision = '7844e2262761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserAddress',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UAid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('UAname', sa.String(length=16), nullable=False),
    sa.Column('UAphone', sa.String(length=16), nullable=False),
    sa.Column('UAtext', sa.String(length=255), nullable=False),
    sa.Column('UApostalcode', sa.String(length=8), nullable=True),
    sa.Column('UAdefault', sa.Boolean(), nullable=True),
    sa.Column('UAisdelete', sa.Boolean(), nullable=True),
    sa.Column('areaid', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('UAid')
    )
    op.add_column('AddressArea', sa.Column('createtime', sa.DateTime(), nullable=True))
    op.add_column('AddressArea', sa.Column('isdelete', sa.Boolean(), nullable=True))
    op.add_column('AddressArea', sa.Column('updatetime', sa.DateTime(), nullable=True))
    op.add_column('AddressCity', sa.Column('createtime', sa.DateTime(), nullable=True))
    op.add_column('AddressCity', sa.Column('isdelete', sa.Boolean(), nullable=True))
    op.add_column('AddressCity', sa.Column('updatetime', sa.DateTime(), nullable=True))
    op.add_column('AddressProvince', sa.Column('createtime', sa.DateTime(), nullable=True))
    op.add_column('AddressProvince', sa.Column('isdelete', sa.Boolean(), nullable=True))
    op.add_column('AddressProvince', sa.Column('updatetime', sa.DateTime(), nullable=True))
    op.add_column('User', sa.Column('USqrcode', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'USqrcode')
    op.drop_column('AddressProvince', 'updatetime')
    op.drop_column('AddressProvince', 'isdelete')
    op.drop_column('AddressProvince', 'createtime')
    op.drop_column('AddressCity', 'updatetime')
    op.drop_column('AddressCity', 'isdelete')
    op.drop_column('AddressCity', 'createtime')
    op.drop_column('AddressArea', 'updatetime')
    op.drop_column('AddressArea', 'isdelete')
    op.drop_column('AddressArea', 'createtime')
    op.drop_table('UserAddress')
    # ### end Alembic commands ###
