"""'add'

Revision ID: 35475b80cf4c
Revises: 1e2c8f0e9731
Create Date: 2019-04-11 23:50:30.563936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35475b80cf4c'
down_revision = '1e2c8f0e9731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrderMainContent',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OCAid', sa.String(length=64), nullable=False),
    sa.Column('CAfrom', sa.Integer(), nullable=True),
    sa.Column('OPid', sa.String(length=64), nullable=True),
    sa.Column('OCAcontentid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('OCAid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderMainContent')
    # ### end Alembic commands ###
