"""激活码2

Revision ID: 38f3f991ee62
Revises: 861c6bc7f1ae
Create Date: 2018-12-12 21:47:25.934860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38f3f991ee62'
down_revision = '861c6bc7f1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserActivationCode',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UACid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('UACcode', sa.String(length=16), nullable=False),
    sa.Column('UACstatus', sa.Integer(), nullable=True),
    sa.Column('UACuseFor', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('UACid')
    )
    op.drop_table('user_activation_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activation_code',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('UACid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('USid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('UACcode', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('UACstatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('UACuseFor', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('UACid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('UserActivationCode')
    # ### end Alembic commands ###
