"""macgixbox_apply_add_source

Revision ID: 3921655d9519
Revises: 55007e2b0d57
Create Date: 2018-12-31 13:00:38.467188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3921655d9519'
down_revision = '55007e2b0d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MagicBoxApply', sa.Column('MBAfrom', sa.Integer(), nullable=True))
    op.add_column('MagicBoxApply', sa.Column('SKUstock', sa.Integer(), nullable=True))
    op.add_column('TrialCommodity', sa.Column('TCfrom', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TrialCommodity', 'TCfrom')
    op.drop_column('MagicBoxApply', 'SKUstock')
    op.drop_column('MagicBoxApply', 'MBAfrom')
    # ### end Alembic commands ###
