"""'add'

Revision ID: 3aa068e88568
Revises: 63425bc93a32
Create Date: 2018-11-14 18:31:18.543517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa068e88568'
down_revision = '63425bc93a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Approval',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('AVid', sa.String(length=64), nullable=False),
    sa.Column('AVname', sa.String(length=255), nullable=False),
    sa.Column('AVtype', sa.Integer(), nullable=True),
    sa.Column('AVstartid', sa.String(length=64), nullable=False),
    sa.Column('AVlevel', sa.String(length=64), nullable=True),
    sa.Column('AVstatus', sa.Integer(), nullable=True),
    sa.Column('AVcontent', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('AVid')
    )
    op.create_table('ApprovalNotes',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ANid', sa.String(length=64), nullable=False),
    sa.Column('AVid', sa.String(length=64), nullable=True),
    sa.Column('AVadname', sa.Text(), nullable=True),
    sa.Column('ADid', sa.String(length=64), nullable=True),
    sa.Column('ANaction', sa.Integer(), nullable=True),
    sa.Column('ANabo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ANid')
    )
    op.create_table('Permission',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PEid', sa.String(length=64), nullable=False),
    sa.Column('ADid', sa.String(length=64), nullable=False),
    sa.Column('PEtype', sa.Integer(), nullable=False),
    sa.Column('PELevel', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('PEid')
    )
    op.add_column('Products', sa.Column('PRdescription', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'PRdescription')
    op.drop_table('Permission')
    op.drop_table('ApprovalNotes')
    op.drop_table('Approval')
    # ### end Alembic commands ###
