"""优惠券加字段

Revision ID: 3acfc68d3192
Revises: 8a59829d0978
Create Date: 2018-11-18 20:02:50.042934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3acfc68d3192'
down_revision = '8a59829d0978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Coupon', sa.Column('COuseNum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Coupon', 'COuseNum')
    # ### end Alembic commands ###
