"""订单加字段

Revision ID: 3f1a1dd891f1
Revises: bbad4c7677e1
Create Date: 2019-01-10 01:20:10.084126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1a1dd891f1'
down_revision = 'bbad4c7677e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderPart', sa.Column('PCname', sa.String(length=255), nullable=True))
    op.add_column('OrderPart', sa.Column('SKUsn', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderPart', 'SKUsn')
    op.drop_column('OrderPart', 'PCname')
    # ### end Alembic commands ###
