"""修改表名

Revision ID: 407dd91aec9e
Revises: 89ca856f4d18
Create Date: 2018-11-05 22:04:03.313245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '407dd91aec9e'
down_revision = '89ca856f4d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Items',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ITid', sa.String(length=64), nullable=False),
    sa.Column('PSid', sa.String(length=64), nullable=False),
    sa.Column('ITname', sa.String(length=16), nullable=False),
    sa.Column('ITsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ITid')
    )
    op.drop_table('ProductSceneItems')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductSceneItems',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('ITid', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('PSid', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('ITname', mysql.VARCHAR(collation='utf8_bin', length=16), nullable=False),
    sa.Column('ITsort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ITid'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('Items')
    # ### end Alembic commands ###
