"""'add'

Revision ID: 4125e69d372b
Revises: 0c1c21e7a42a
Create Date: 2018-11-16 00:02:58.135306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4125e69d372b'
down_revision = '0c1c21e7a42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserLoginTime', sa.Column('ULtype', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserLoginTime', 'ULtype')
    # ### end Alembic commands ###
