"""活动控制

Revision ID: 419168dba794
Revises: 7af732329e28
Create Date: 2018-11-29 16:01:32.246824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419168dba794'
down_revision = '7af732329e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Activity',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ACid', sa.String(length=64), nullable=False),
    sa.Column('ACbackGround', sa.String(length=255), nullable=False),
    sa.Column('ACbutton', sa.String(length=16), nullable=True),
    sa.Column('ACtype', sa.Integer(), nullable=True),
    sa.Column('ACshow', sa.Boolean(), nullable=True),
    sa.Column('ACdesc', sa.String(length=255), nullable=True),
    sa.Column('ACname', sa.String(length=16), nullable=False),
    sa.Column('ACsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ACid')
    )
    op.create_index(op.f('ix_Activity_ACtype'), 'Activity', ['ACtype'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Activity_ACtype'), table_name='Activity')
    op.drop_table('Activity')
    # ### end Alembic commands ###
