"""'add'

Revision ID: 44b846942959
Revises: c1a3e4f38453
Create Date: 2019-02-24 15:36:22.094259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44b846942959'
down_revision = 'c1a3e4f38453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GuessNumAwardProduct',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('GNAPid', sa.String(length=64), nullable=False),
    sa.Column('GNAAid', sa.String(length=64), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('PRmainpic', sa.String(length=255), nullable=False),
    sa.Column('PRtitle', sa.String(length=255), nullable=False),
    sa.Column('PBid', sa.String(length=64), nullable=False),
    sa.Column('PBname', sa.String(length=64), nullable=False),
    sa.Column('PRattribute', sa.String(length=255), nullable=True),
    sa.Column('PRdescription', sa.Text(), nullable=True),
    sa.Column('PRfeight', sa.Float(), nullable=True),
    sa.Column('PRprice', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('GNAPid')
    )
    op.create_table('GuessNumAwardSku',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('GNASid', sa.String(length=64), nullable=False),
    sa.Column('GNAPid', sa.String(length=64), nullable=True),
    sa.Column('SKUid', sa.String(length=64), nullable=False),
    sa.Column('SKUprice', sa.Float(), nullable=False),
    sa.Column('SKUdiscountone', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SKUdiscounttwo', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SKUdiscountthree', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SKUdiscountfour', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SKUdiscountfive', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SKUdiscountsix', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('GNASid')
    )
    op.drop_column('GuessNumAward', 'SKUprice')
    op.drop_column('GuessNumAward', 'SKUid')
    op.drop_column('GuessNumAward', 'PRid')
    op.drop_column('GuessNumAward', 'OSid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GuessNumAward', sa.Column('OSid', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('GuessNumAward', sa.Column('PRid', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('GuessNumAward', sa.Column('SKUid', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('GuessNumAward', sa.Column('SKUprice', mysql.FLOAT(), nullable=True))
    op.drop_table('GuessNumAwardSku')
    op.drop_table('GuessNumAwardProduct')
    # ### end Alembic commands ###
