"""激活码购买字段和规则

Revision ID: 459be37c2041
Revises: 38f3f991ee62
Create Date: 2018-12-13 10:16:29.645215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '459be37c2041'
down_revision = '38f3f991ee62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ActivationCodeRule',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ACRid', sa.String(length=64), nullable=False),
    sa.Column('ACRrule', sa.Text(), nullable=True),
    sa.Column('ACRphone', sa.String(length=11), nullable=True),
    sa.Column('ACRaddress', sa.String(length=64), nullable=True),
    sa.Column('ACRname', sa.String(length=16), nullable=False),
    sa.Column('ACRbankSn', sa.String(length=32), nullable=False),
    sa.Column('ACRbankAddress', sa.String(length=125), nullable=False),
    sa.Column('ACRAgreeMent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ACRid')
    )
    op.add_column('ActivationCodeApply', sa.Column('ACRbankAddress', sa.String(length=125), nullable=False))
    op.add_column('ActivationCodeApply', sa.Column('ACRbankSn', sa.String(length=32), nullable=False))
    op.add_column('ActivationCodeApply', sa.Column('ACRname', sa.String(length=32), nullable=False))
    op.drop_column('ActivationCodeApply', 'ACAnum')
    op.drop_column('ActivationCodeApply', 'ACAaddress')
    op.drop_column('ActivationCodeApply', 'ACAname')
    op.create_index(op.f('ix_UserActivationCode_USid'), 'UserActivationCode', ['USid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserActivationCode_USid'), table_name='UserActivationCode')
    op.add_column('ActivationCodeApply', sa.Column('ACAname', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('ActivationCodeApply', sa.Column('ACAaddress', mysql.VARCHAR(length=125), nullable=False))
    op.add_column('ActivationCodeApply', sa.Column('ACAnum', mysql.VARCHAR(length=32), nullable=False))
    op.drop_column('ActivationCodeApply', 'ACRname')
    op.drop_column('ActivationCodeApply', 'ACRbankSn')
    op.drop_column('ActivationCodeApply', 'ACRbankAddress')
    op.drop_table('ActivationCodeRule')
    # ### end Alembic commands ###
