"""物流

Revision ID: 49543bb8bdde
Revises: 5ee7612cc95f
Create Date: 2018-11-12 10:33:31.872779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49543bb8bdde'
down_revision = '5ee7612cc95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrderLogistics',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OLid', sa.String(length=64), nullable=False),
    sa.Column('OMid', sa.String(length=64), nullable=False),
    sa.Column('OPid', sa.String(length=125), nullable=True),
    sa.Column('OLcompany', sa.String(length=32), nullable=False),
    sa.Column('OLexpressNo', sa.String(length=64), nullable=False),
    sa.Column('OLsearchStatus', sa.String(length=8), nullable=True),
    sa.Column('OLsignStatus', sa.Integer(), nullable=True),
    sa.Column('OLdata', sa.Text(), nullable=True),
    sa.Column('OLlastresult', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('OLid')
    )
    op.add_column('OrderRefund', sa.Column('OPid', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderRefund', 'OPid')
    op.drop_table('OrderLogistics')
    # ### end Alembic commands ###
