"""'add'

Revision ID: 51e235168984
Revises: aa66e1bbe506
Create Date: 2019-04-03 15:00:14.212206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e235168984'
down_revision = 'aa66e1bbe506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CounponHistory',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('CHid', sa.String(length=64), nullable=False),
    sa.Column('COid', sa.String(length=64), nullable=True),
    sa.Column('COcontent', sa.Text(), nullable=True),
    sa.Column('COaction', sa.Integer(), nullable=True),
    sa.Column('CHuser', sa.String(length=64), nullable=True),
    sa.Column('CHuserType', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('CHid')
    )
    op.create_table('SupplizerDepositLog',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SDLid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.Column('SDLnum', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SDafter', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SDbefore', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SDLacid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('SDLid')
    )
    op.add_column('Supplizer', sa.Column('SUdeposit', sa.DECIMAL(precision=28, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Supplizer', 'SUdeposit')
    op.drop_table('SupplizerDepositLog')
    op.drop_table('CounponHistory')
    # ### end Alembic commands ###
