"""提现字段

Revision ID: 5233dd0ace6b
Revises: a25cdd3dbe1e
Create Date: 2019-01-08 20:50:29.294154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5233dd0ace6b'
down_revision = 'a25cdd3dbe1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
