"""index fix

Revision ID: 525c1879e9c7
Revises: f253540e29c4
Create Date: 2018-11-12 13:29:17.830662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525c1879e9c7'
down_revision = 'f253540e29c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IndexBrand', sa.Column('IBshow', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('IndexBrand', 'IBshow')
    # ### end Alembic commands ###
