"""add column

Revision ID: 55007e2b0d57
Revises: be8935948169
Create Date: 2018-12-31 11:59:39.991678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55007e2b0d57'
down_revision = 'be8935948169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FreshManFirstApply', sa.Column('FMFAfrom', sa.Integer(), nullable=True))
    op.add_column('FreshManFirstSku', sa.Column('FMFPstock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FreshManFirstSku', 'FMFPstock')
    op.drop_column('FreshManFirstApply', 'FMFAfrom')
    # ### end Alembic commands ###
