"""激活码加字段

Revision ID: 553a3b282001
Revises: e93b65883580
Create Date: 2018-12-13 17:31:21.614294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553a3b282001'
down_revision = 'e93b65883580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserActivationCode', sa.Column('UACtime', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_UserActivationCode_UACcode'), 'UserActivationCode', ['UACcode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserActivationCode_UACcode'), table_name='UserActivationCode')
    op.drop_column('UserActivationCode', 'UACtime')
    # ### end Alembic commands ###
