"""订单售后test

Revision ID: 56561a14e9b5
Revises: c0ac37fe9386
Create Date: 2018-11-21 16:34:26.814764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56561a14e9b5'
down_revision = 'c0ac37fe9386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
