"""供应商佣金

Revision ID: 5a8d3fe30306
Revises: 6e3c1cae4071
Create Date: 2019-01-06 15:07:41.248430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8d3fe30306'
down_revision = '6e3c1cae4071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SignInAward',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SIAid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('SIAid')
    )
    op.add_column('UserCommission', sa.Column('CommisionFor', sa.Integer(), nullable=True))
    op.add_column('UserWallet', sa.Column('CommisionFor', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserWallet', 'CommisionFor')
    op.drop_column('UserCommission', 'CommisionFor')
    op.drop_table('SignInAward')
    # ### end Alembic commands ###
