"""附单优惠券1

Revision ID: 5ab0f8b34e54
Revises: 5b0167f76f58
Create Date: 2019-01-09 00:31:23.898296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab0f8b34e54'
down_revision = '5b0167f76f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderRaward', sa.Column('SUid', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderRaward', 'SUid')
    # ### end Alembic commands ###
