"""附单优惠券

Revision ID: 5b0167f76f58
Revises: bb60cb9d1c75
Create Date: 2019-01-09 00:13:39.782297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0167f76f58'
down_revision = 'bb60cb9d1c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderPart', sa.Column('UseCoupon', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderPart', 'UseCoupon')
    # ### end Alembic commands ###
