"""createid 

Revision ID: 5e296d2991ae
Revises: cb0a9dfe00d4
Create Date: 2018-11-19 09:17:58.982553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e296d2991ae'
down_revision = 'cb0a9dfe00d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderMain', sa.Column('PRcreateId', sa.String(length=64), nullable=True))
    op.drop_column('OrderPart', 'PRcreateId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderPart', sa.Column('PRcreateId', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True))
    op.drop_column('OrderMain', 'PRcreateId')
    # ### end Alembic commands ###
