"""add cash notes

Revision ID: 5e6c8417e30b
Revises: b7cf821a7c3d
Create Date: 2018-12-12 12:15:03.712420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e6c8417e30b'
down_revision = 'b7cf821a7c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_notes',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('CNid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('CNbankName', sa.Text(), nullable=True),
    sa.Column('CNbankDetail', sa.Text(), nullable=True),
    sa.Column('CNcardNo', sa.String(length=32), nullable=True),
    sa.Column('CNcashNum', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('CNstatus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('CNid')
    )
    op.drop_table('CashNotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CashNotes',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('CNid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('USid', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('CNbankName', mysql.TEXT(), nullable=True),
    sa.Column('CNbankDetail', mysql.TEXT(), nullable=True),
    sa.Column('CNcardNo', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('CNcashNum', mysql.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('CNstatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('CNid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('cash_notes')
    # ### end Alembic commands ###
