"""'add'

Revision ID: 6061a7f254bc
Revises: c335a587fdfd
Create Date: 2018-12-01 05:23:18.090122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6061a7f254bc'
down_revision = 'c335a587fdfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('QuestAnswerNote',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('QANid', sa.String(length=64), nullable=False),
    sa.Column('QANcontent', sa.Text(), nullable=True),
    sa.Column('QANcreateid', sa.String(length=64), nullable=True),
    sa.Column('QANtargetId', sa.String(length=64), nullable=True),
    sa.Column('QANtype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('QANid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('QuestAnswerNote')
    # ### end Alembic commands ###
