"""'add'

Revision ID: 62233ad25f9f
Revises: f39363d7b427
Create Date: 2019-04-18 11:27:15.769450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62233ad25f9f'
down_revision = 'f39363d7b427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserCollection', sa.Column('UCLcoType', sa.String(length=64), nullable=True))
    op.add_column('UserCollection', sa.Column('UCLcollection', sa.String(length=64), nullable=True))
    op.add_column('UserCollection', sa.Column('UCLcollector', sa.String(length=64), nullable=True))
    op.add_column('UserCollection', sa.Column('UCLid', sa.String(length=64), nullable=False))
    op.drop_column('UserCollection', 'UCOid')
    op.drop_column('UserCollection', 'UCollection')
    op.drop_column('UserCollection', 'UCollector')
    op.drop_column('UserCollection', 'UCoType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserCollection', sa.Column('UCoType', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('UserCollection', sa.Column('UCollector', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('UserCollection', sa.Column('UCollection', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('UserCollection', sa.Column('UCOid', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('UserCollection', 'UCLid')
    op.drop_column('UserCollection', 'UCLcollector')
    op.drop_column('UserCollection', 'UCLcollection')
    op.drop_column('UserCollection', 'UCLcoType')
    # ### end Alembic commands ###
