"""'modify_nvduration_type'

Revision ID: 63425bc93a32
Revises: d96916bb8d72
Create Date: 2018-11-14 16:54:24.932988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63425bc93a32'
down_revision = 'd96916bb8d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
