"""'add'

Revision ID: 63a3654b74cd
Revises: 0ea43f870124
Create Date: 2018-11-07 16:38:20.874173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63a3654b74cd'
down_revision = '0ea43f870124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('USfrom', sa.Integer(), nullable=True))
    op.drop_column('UserCommission', 'UCcreateTime')
    op.drop_column('UserLoginTime', 'USTcreatetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserLoginTime', sa.Column('USTcreatetime', mysql.DATETIME(), nullable=True))
    op.add_column('UserCommission', sa.Column('UCcreateTime', mysql.DATETIME(), nullable=True))
    op.drop_column('User', 'USfrom')
    # ### end Alembic commands ###
