"""add

Revision ID: 657468a4e893
Revises: c61af4aa5626
Create Date: 2019-01-08 15:16:38.803211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657468a4e893'
down_revision = 'c61af4aa5626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Approval', sa.Column('AVcontentdetail', sa.Text(), nullable=True))
    op.add_column('Approval', sa.Column('AVstartdetail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Approval', 'AVstartdetail')
    op.drop_column('Approval', 'AVcontentdetail')
    # ### end Alembic commands ###
