"""魔术礼盒表

Revision ID: 65f6da28d07c
Revises: a4c9d183d767
Create Date: 2018-11-30 16:45:43.392737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65f6da28d07c'
down_revision = 'a4c9d183d767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MagicBoxApply',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('MBAid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=False),
    sa.Column('SKUid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('MBAstarttime', sa.Date(), nullable=False),
    sa.Column('MBAendtime', sa.Date(), nullable=False),
    sa.Column('SKUprice', sa.Float(), nullable=False),
    sa.Column('SKUminPrice', sa.Float(), nullable=False),
    sa.Column('Gearsone', sa.String(length=64), nullable=False),
    sa.Column('Gearstwo', sa.String(length=64), nullable=False),
    sa.Column('Gearsthree', sa.String(length=64), nullable=False),
    sa.Column('MBAstatus', sa.Integer(), autoincrement=0, nullable=True),
    sa.Column('AgreeStartime', sa.Date(), nullable=True),
    sa.Column('AgreeEndtime', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('MBAid')
    )
    op.drop_table('WareHouse')
    op.drop_table('MagicBox')
    op.drop_table('WareHouseInFlow')
    op.drop_table('WareHouseProduct')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WareHouseProduct',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('WHPid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('PRid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('WAid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('PRnum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('WHPid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('WareHouseInFlow',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('WHIFid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('PRid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('SUid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('PRnum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('WHIFid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('MagicBox',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('MBid', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('MBid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('WareHouse',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('WAid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('WAname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('WAphone', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('WAcontact', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('WAaddress', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('WAstatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('WAid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('MagicBoxApply')
    # ### end Alembic commands ###
