"""活动-订单

Revision ID: 661df4a133ac
Revises: 1a901be3889b
Create Date: 2019-01-08 03:16:22.757658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '661df4a133ac'
down_revision = '1a901be3889b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GuessNum', sa.Column('GNNAid', sa.String(length=64), nullable=True))
    op.drop_column('GuessNum', 'GNAAid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GuessNum', sa.Column('GNAAid', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('GuessNum', 'GNNAid')
    # ### end Alembic commands ###
