"""'add'

Revision ID: 6748e99cc2f8
Revises: 2a0cfc521241
Create Date: 2018-12-29 18:23:49.404621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6748e99cc2f8'
down_revision = '2a0cfc521241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CashNotes', sa.Column('CNrejectReason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CashNotes', 'CNrejectReason')
    # ### end Alembic commands ###
