"""product add score

Revision ID: 6c3bc5e0c5b9
Revises: 56561a14e9b5
Create Date: 2018-11-21 17:00:25.578009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3bc5e0c5b9'
down_revision = '56561a14e9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('PRaverageScore', sa.Float(precision=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'PRaverageScore')
    # ### end Alembic commands ###
