"""提现加字段

Revision ID: 6d2d45a716f5
Revises: 2b7923d19eb6
Create Date: 2018-12-20 16:39:53.430802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2d45a716f5'
down_revision = '2b7923d19eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CashNotes', sa.Column('CNcardName', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CashNotes', 'CNcardName')
    # ### end Alembic commands ###
