"""'add'

Revision ID: 6d4b37cfa46b
Revises: 2db37d59cdec
Create Date: 2019-04-10 11:42:45.121080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4b37cfa46b'
down_revision = '2db37d59cdec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TimeLimitedApply', sa.Column('TLAsort', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TimeLimitedApply', 'TLAsort')
    # ### end Alembic commands ###
