"""快递自增字段

Revision ID: 6e102472ae2d
Revises: 400d41d93fdc
Create Date: 2018-11-12 18:18:01.057512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e102472ae2d'
down_revision = '400d41d93fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LogisticsCompnay', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('LogisticsCompnay', '_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LogisticsCompnay', sa.Column('_id', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('LogisticsCompnay', 'id')
    # ### end Alembic commands ###
