"""test

Revision ID: 70cb84ad6d9a
Revises: 81c1339c60d0
Create Date: 2018-11-13 14:34:40.016424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70cb84ad6d9a'
down_revision = '81c1339c60d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IDcheck',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('IDCid', sa.String(length=64), nullable=False),
    sa.Column('IDCcode', sa.String(length=24), nullable=False),
    sa.Column('IDCname', sa.Text(), nullable=True),
    sa.Column('IDCresult', sa.Boolean(), nullable=True),
    sa.Column('IDCrealName', sa.Text(), nullable=True),
    sa.Column('IDCcardNo', sa.Text(), nullable=True),
    sa.Column('IDCaddrCode', sa.Text(), nullable=True),
    sa.Column('IDCbirth', sa.Text(), nullable=True),
    sa.Column('IDCsex', sa.Integer(), nullable=True),
    sa.Column('IDCcheckBit', sa.String(length=2), nullable=True),
    sa.Column('IDCaddr', sa.Text(), nullable=True),
    sa.Column('IDCerrorCode', sa.String(length=8), nullable=True),
    sa.Column('IDCreason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('IDCid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('IDcheck')
    # ### end Alembic commands ###
