"""brand背景图

Revision ID: 724fc23e13ff
Revises: 786885130f20
Create Date: 2018-11-15 11:06:00.607107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '724fc23e13ff'
down_revision = '786885130f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Coupon', 'COname',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.add_column('ProductBrand', sa.Column('PBbackgroud', sa.String(length=255), nullable=True))
    op.add_column('ProductSkuValue', sa.Column('PCid', sa.String(length=64), nullable=False))
    op.drop_column('ProductSkuValue', 'PRid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProductSkuValue', sa.Column('PRid', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False))
    op.drop_column('ProductSkuValue', 'PCid')
    op.drop_column('ProductBrand', 'PBbackgroud')
    op.alter_column('Coupon', 'COname',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###
