"""快递列表

Revision ID: 75d61cf45fad
Revises: 06496384940f
Create Date: 2018-12-07 17:23:00.045933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75d61cf45fad'
down_revision = '06496384940f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FreshManFirstSku', 'SKUpic')
    op.add_column('LogisticsCompnay', sa.Column('LCfirstCharater', sa.String(length=1), nullable=False))
    op.add_column('LogisticsCompnay', sa.Column('LCisCommon', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_LogisticsCompnay_LCfirstCharater'), 'LogisticsCompnay', ['LCfirstCharater'], unique=False)
    op.drop_index('ix_LogisticsCompnay_LCname', table_name='LogisticsCompnay')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_LogisticsCompnay_LCname', 'LogisticsCompnay', ['LCname'], unique=False)
    op.drop_index(op.f('ix_LogisticsCompnay_LCfirstCharater'), table_name='LogisticsCompnay')
    op.drop_column('LogisticsCompnay', 'LCisCommon')
    op.drop_column('LogisticsCompnay', 'LCfirstCharater')
    op.add_column('FreshManFirstSku', sa.Column('SKUpic', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
