"""item标签

Revision ID: 76d737a80d9d
Revises: e5d79197d8f0
Create Date: 2018-11-09 18:57:22.629024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76d737a80d9d'
down_revision = 'e5d79197d8f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Items', sa.Column('ITtype', sa.Integer(), nullable=True))
    op.alter_column('Items', 'PSid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=True)
    op.create_index(op.f('ix_Items_ITtype'), 'Items', ['ITtype'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Items_ITtype'), table_name='Items')
    op.alter_column('Items', 'PSid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=False)
    op.drop_column('Items', 'ITtype')
    # ### end Alembic commands ###
