"""'add'

Revision ID: 799df421cc4a
Revises: d2684f69dfbb
Create Date: 2018-11-22 19:55:55.532528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '799df421cc4a'
down_revision = 'd2684f69dfbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('USCommission1', sa.Float(), nullable=True))
    op.add_column('User', sa.Column('USCommission2', sa.Float(), nullable=True))
    op.alter_column('User', 'UStelphone',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=13),
               nullable=True)
    op.drop_column('User', 'USCommission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('USCommission', mysql.FLOAT(), nullable=True))
    op.alter_column('User', 'UStelphone',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=13),
               nullable=False)
    op.drop_column('User', 'USCommission2')
    op.drop_column('User', 'USCommission1')
    # ### end Alembic commands ###
