"""优惠券修改

Revision ID: 7af732329e28
Revises: 163e60d386bc
Create Date: 2018-11-28 13:37:45.900195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7af732329e28'
down_revision = '163e60d386bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CouponFor',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('CFid', sa.String(length=64), nullable=False),
    sa.Column('PCid', sa.String(length=64), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=True),
    sa.Column('PBid', sa.String(length=64), nullable=True),
    sa.Column('COid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('CFid')
    )
    op.drop_column('Coupon', 'PBid')
    op.drop_column('Coupon', 'PCid')
    op.drop_column('Coupon', 'PRid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Coupon', sa.Column('PRid', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('Coupon', sa.Column('PCid', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('Coupon', sa.Column('PBid', mysql.VARCHAR(length=64), nullable=True))
    op.drop_table('CouponFor')
    # ### end Alembic commands ###
