"""model类型错误

Revision ID: 7ccde67e8aaf
Revises: a3860abbd4f0
Create Date: 2018-11-21 22:12:19.727168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ccde67e8aaf'
down_revision = 'a3860abbd4f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
