"""商品添加精选字段

Revision ID: 818011ad3817
Revises: ba2398443bfb
Create Date: 2019-03-11 22:34:07.222020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818011ad3817'
down_revision = 'ba2398443bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('PRfeatured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'PRfeatured')
    # ### end Alembic commands ###
