""" url and url_list

Revision ID: 81c1339c60d0
Revises: c0eb8458afd1
Create Date: 2018-11-12 20:59:46.373033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c1339c60d0'
down_revision = 'c0eb8458afd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
