"""'fix_news'

Revision ID: 82138cb190a8
Revises: c00045b9953a
Create Date: 2018-11-12 19:32:10.818815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82138cb190a8'
down_revision = 'c00045b9953a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
