"""o

Revision ID: 8596c32a2195
Revises: 37e66b0c8e53
Create Date: 2018-11-07 19:14:59.049317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8596c32a2195'
down_revision = '37e66b0c8e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderRefundApply', sa.Column('ORAaddtion', sa.String(length=255), nullable=True))
    op.add_column('OrderRefundApply', sa.Column('ORAmount', sa.Float(), nullable=False))
    op.add_column('OrderRefundApply', sa.Column('ORaddtionVoucher', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderRefundApply', 'ORaddtionVoucher')
    op.drop_column('OrderRefundApply', 'ORAmount')
    op.drop_column('OrderRefundApply', 'ORAaddtion')
    # ### end Alembic commands ###
