"""'add'

Revision ID: 85fc69dd43c5
Revises: b0e77aa1e884
Create Date: 2019-04-24 12:25:15.645405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85fc69dd43c5'
down_revision = 'b0e77aa1e884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CouponCode',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('CCid', sa.String(length=64), nullable=False),
    sa.Column('COid', sa.String(length=64), nullable=False),
    sa.Column('CCcode', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('CCid')
    )
    op.create_table('Entry',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ENid', sa.String(length=64), nullable=False),
    sa.Column('ENpic', sa.Text(), nullable=True),
    sa.Column('ENshow', sa.Boolean(), nullable=True),
    sa.Column('contentlink', mysql.LONGTEXT(), nullable=True),
    sa.Column('ACid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ENid')
    )
    op.add_column('Coupon', sa.Column('COcode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Coupon', 'COcode')
    op.drop_table('Entry')
    op.drop_table('CouponCode')
    # ### end Alembic commands ###
