"""激活码1

Revision ID: 861c6bc7f1ae
Revises: 86249c141d58
Create Date: 2018-12-12 21:45:40.740451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861c6bc7f1ae'
down_revision = '86249c141d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ActivationCodeApply',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ACAid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('ACAname', sa.String(length=32), nullable=False),
    sa.Column('ACAnum', sa.String(length=32), nullable=False),
    sa.Column('ACAaddress', sa.String(length=125), nullable=False),
    sa.Column('ACAvouchers', sa.Text(), nullable=True),
    sa.Column('ACAapplyStatus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ACAid')
    )
    op.create_table('user_activation_code',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UACid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('UACcode', sa.String(length=16), nullable=False),
    sa.Column('UACstatus', sa.Integer(), nullable=True),
    sa.Column('UACuseFor', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('UACid')
    )
    op.add_column('ProductSku', sa.Column('SKUsn', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ProductSku', 'SKUsn')
    op.drop_table('user_activation_code')
    op.drop_table('ActivationCodeApply')
    # ### end Alembic commands ###
