"""分类顶部图

Revision ID: 86249c141d58
Revises: c1cf84e27d46
Create Date: 2018-12-12 19:40:46.168699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86249c141d58'
down_revision = 'c1cf84e27d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
