"""cashflow

Revision ID: 87baff208d84
Revises: 50c66b8fd001
Create Date: 2019-04-30 14:51:10.845979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87baff208d84'
down_revision = '50c66b8fd001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CashFlow',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('CFWid', sa.String(length=64), nullable=False),
    sa.Column('CNid', sa.String(length=64), nullable=False),
    sa.Column('partner_trade_no', sa.String(length=64), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('amout', sa.Integer(), nullable=True),
    sa.Column('cmms_amt', sa.Integer(), nullable=True),
    sa.Column('CFWfrom', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('CFWid')
    )
    op.drop_column('CouponCode', 'CCused')
    op.drop_column('Entry', 'ENtype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Entry', sa.Column('ENtype', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('CouponCode', sa.Column('CCused', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_table('CashFlow')
    # ### end Alembic commands ###
