"""modify

Revision ID: 89ca856f4d18
Revises: a84bf80f8d7f
Create Date: 2018-11-05 18:42:59.482753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89ca856f4d18'
down_revision = 'a84bf80f8d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderPart', sa.Column('PRattribute', sa.Text(), nullable=True))
    op.add_column('OrderPart', sa.Column('SKUattriteDetail', sa.Text(), nullable=False))
    op.drop_column('OrderPart', 'SKUdetail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderPart', sa.Column('SKUdetail', mysql.TEXT(collation='utf8_bin'), nullable=False))
    op.drop_column('OrderPart', 'SKUattriteDetail')
    op.drop_column('OrderPart', 'PRattribute')
    # ### end Alembic commands ###
