"""'add'

Revision ID: 8a4e12f109b8
Revises: 5a8d3fe30306
Create Date: 2019-01-07 01:47:37.720997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4e12f109b8'
down_revision = '5a8d3fe30306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserWallet', sa.Column('UWcash', sa.DECIMAL(precision=28, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserWallet', 'UWcash')
    # ### end Alembic commands ###
