"""'add'

Revision ID: 8a59829d0978
Revises: beeef33e976c
Create Date: 2018-11-16 13:47:17.412447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a59829d0978'
down_revision = 'beeef33e976c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('USpaycode', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'USpaycode')
    # ### end Alembic commands ###
