"""delete 

Revision ID: 8ab0a32f9e9b
Revises: daed9a4ea3d2
Create Date: 2018-11-05 09:52:14.898359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ab0a32f9e9b'
down_revision = 'daed9a4ea3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderPay', 'OPaybody')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderPay', sa.Column('OPaybody', mysql.VARCHAR(collation='utf8_bin', length=255), nullable=True))
    # ### end Alembic commands ###
