"""'add'

Revision ID: 8b2cf082e550
Revises: 35475b80cf4c
Create Date: 2019-04-17 16:56:33.139965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2cf082e550'
down_revision = '35475b80cf4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
