"""modify_commodity_freight

Revision ID: 8b86d923c880
Revises: fd498cf63c6a
Create Date: 2018-11-27 15:41:50.130151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b86d923c880'
down_revision = 'fd498cf63c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TrialCommodity', sa.Column('TCfreight', sa.Float(), nullable=True))
    op.drop_column('TrialCommodity', 'PRfreight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TrialCommodity', sa.Column('PRfreight', mysql.FLOAT(), nullable=True))
    op.drop_column('TrialCommodity', 'TCfreight')
    # ### end Alembic commands ###
