"""added two columns to person table

Revision ID: 911d3877424c
Revises: 
Create Date: 2018-11-02 12:09:45.451998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '911d3877424c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrderMain',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OMid', sa.String(length=64), nullable=False),
    sa.Column('OMno', sa.String(length=64), nullable=False),
    sa.Column('OPayid', sa.String(length=64), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('UseCoupon', sa.Boolean(), nullable=True),
    sa.Column('OMfrom', sa.Integer(), nullable=True),
    sa.Column('PBname', sa.String(length=32), nullable=False),
    sa.Column('PBid', sa.String(length=64), nullable=False),
    sa.Column('OMclient', sa.Integer(), nullable=True),
    sa.Column('OMfreight', sa.Float, nullable=True),
    sa.Column('OMmount', sa.Float(), nullable=False),
    sa.Column('OMtrueMount', sa.Float(), nullable=False),
    sa.Column('OMstatus', sa.Integer(), nullable=True),
    sa.Column('OMmessage', sa.String(length=255), nullable=True),
    sa.Column('OMrecvPhone', sa.String(length=11), nullable=False),
    sa.Column('OMrecvName', sa.String(length=11), nullable=False),
    sa.Column('OMrecvAddress', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('OMid')
    )
    op.create_table('OrderPart',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OPid', sa.String(length=64), nullable=False),
    sa.Column('OMid', sa.String(length=64), nullable=False),
    sa.Column('SKUid', sa.String(length=64), nullable=False),
    sa.Column('SKUdetail', sa.Text(), nullable=False),
    sa.Column('SKUprice', sa.Float(), nullable=False),
    sa.Column('PRtitle', sa.String(length=255), nullable=False),
    sa.Column('PRmainpic', sa.String(length=255), nullable=False),
    sa.Column('OPnum', sa.Integer(), nullable=True),
    sa.Column('OPsubTotal', sa.Float(), nullable=True),
    sa.Column('OPstatus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('OPid')
    )
    op.create_table('OrderPay',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OPayid', sa.String(length=64), nullable=False),
    sa.Column('OPsn', sa.String(length=64), nullable=True),
    sa.Column('OPayType', sa.Integer(), nullable=True),
    sa.Column('OPaytime', sa.DateTime(), nullable=True),
    sa.Column('OPayMount', sa.Integer(), nullable=True),
    sa.Column('OPaysn', sa.String(length=64), nullable=True),
    sa.Column('OPayJson', sa.Text(), nullable=True),
    sa.Column('OPmarks', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('OPayid')
    )
    op.create_table('OrderRaward',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OCid', sa.String(length=64), nullable=False),
    sa.Column('CPid', sa.String(length=64), nullable=False),
    sa.Column('OCnum', sa.Integer(), nullable=True),
    sa.Column('OCreduce', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('OCid')
    )
    op.alter_column('ProductCategory', 'PCname',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=16),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ProductCategory', 'PCname',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=16),
               nullable=True)
    op.drop_table('OrderRaward')
    op.drop_table('OrderPay')
    op.drop_table('OrderPart')
    op.drop_table('OrderMain')
    # ### end Alembic commands ###
