"""新人参与添加冗余字段

Revision ID: 915526dd2a4f
Revises: dcf3926400e6
Create Date: 2018-12-11 10:02:44.979681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915526dd2a4f'
down_revision = 'dcf3926400e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FreshManJoinFlow', sa.Column('OMprice', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FreshManJoinFlow', 'OMprice')
    # ### end Alembic commands ###
