"""'add'

Revision ID: 96e7be500f3f
Revises: 7587324f3796
Create Date: 2019-04-23 12:08:40.648067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96e7be500f3f'
down_revision = '7587324f3796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HypermarketIndexBanner',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('HIBid', sa.String(length=64), nullable=False),
    sa.Column('HIBpic', sa.String(length=255), nullable=False),
    sa.Column('HIBsort', sa.Integer(), nullable=True),
    sa.Column('HIBshow', sa.Boolean(), nullable=True),
    sa.Column('contentlink', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('HIBid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('HypermarketIndexBanner')
    # ### end Alembic commands ###
