"""pay

Revision ID: 98dcbe12bb58
Revises: ac17508b7ec7
Create Date: 2018-11-02 13:45:18.924204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98dcbe12bb58'
down_revision = 'ac17508b7ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
