"""'add'

Revision ID: 994be0019948
Revises: 5eacb635710f
Create Date: 2019-03-21 17:02:56.612575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994be0019948'
down_revision = '5eacb635710f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
