"""标签修改

Revision ID: 9d8c4f216f3c
Revises: 76d737a80d9d
Create Date: 2018-11-09 19:14:20.326816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d8c4f216f3c'
down_revision = '76d737a80d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BrandItems')
    op.add_column('BrandwithItems', sa.Column('ITid', sa.String(length=64), nullable=False))
    op.drop_column('BrandwithItems', 'BIid')
    op.add_column('Items', sa.Column('ITdesc', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Items', 'ITdesc')
    op.add_column('BrandwithItems', sa.Column('BIid', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('BrandwithItems', 'ITid')
    op.create_table('BrandItems',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('BIid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('BIname', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('BIsort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('BIdesc', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('BIid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
