"""search history

Revision ID: 9f27301bfebc
Revises: 261fdf11108a
Create Date: 2018-11-06 18:23:54.349487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f27301bfebc'
down_revision = '261fdf11108a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserSearchHistory',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('USHid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('USHname', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('USHid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserSearchHistory')
    # ### end Alembic commands ###
