"""供应商提现流水

Revision ID: a25cdd3dbe1e
Revises: 657468a4e893
Create Date: 2019-01-08 19:17:18.491726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a25cdd3dbe1e'
down_revision = '657468a4e893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CashNotes', sa.Column('CommisionFor', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CashNotes', 'CommisionFor')
    # ### end Alembic commands ###
