"""标签

Revision ID: a3860abbd4f0
Revises: a7e0e77228f0
Create Date: 2018-11-21 21:29:55.350194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3860abbd4f0'
down_revision = 'a7e0e77228f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SceneItem',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SIid', sa.String(length=64), nullable=False),
    sa.Column('PSid', sa.String(length=64), nullable=False),
    sa.Column('ITid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('SIid')
    )
    op.drop_column('Items', 'PSid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Items', sa.Column('PSid', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True))
    op.drop_table('SceneItem')
    # ### end Alembic commands ###
