"""活动

Revision ID: a4c9d183d767
Revises: 419168dba794
Create Date: 2018-11-29 16:30:50.870513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c9d183d767'
down_revision = '419168dba794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Activity', sa.Column('ACtopPic', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Activity', 'ACtopPic')
    # ### end Alembic commands ###
