"""add_news_source

Revision ID: a7e0e77228f0
Revises: e715f346ce47
Create Date: 2018-11-21 19:57:45.943783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e0e77228f0'
down_revision = 'e715f346ce47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('News', sa.Column('NEsource', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('News', 'NEsource')
    # ### end Alembic commands ###
