"""'add'

Revision ID: a9988ebee73d
Revises: 87baff208d84
Create Date: 2019-05-05 18:47:36.646207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9988ebee73d'
down_revision = '87baff208d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CouponCode', sa.Column('CCused', sa.Boolean(), nullable=True))
    op.add_column('Entry', sa.Column('ENtype', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Entry', 'ENtype')
    op.drop_column('CouponCode', 'CCused')
    # ### end Alembic commands ###
