"""'news_url_modify'

Revision ID: ab2ee1ae6140
Revises: 70cb84ad6d9a
Create Date: 2018-11-13 21:49:38.747432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2ee1ae6140'
down_revision = '70cb84ad6d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IndexHotProduct',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('IHPid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('IHPsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('IHPid')
    )
    op.add_column('NewsVideo', sa.Column('NVthumbnail', sa.String(length=255), nullable=False))
    op.add_column('OrderMain', sa.Column('PRfrom', sa.Integer(), nullable=True))
    op.add_column('OrderMain', sa.Column('UPperid', sa.String(length=64), nullable=True))
    op.add_column('OrderMain', sa.Column('UPperid2', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderMain', 'UPperid2')
    op.drop_column('OrderMain', 'UPperid')
    op.drop_column('OrderMain', 'PRfrom')
    op.drop_column('NewsVideo', 'NVthumbnail')
    op.drop_table('IndexHotProduct')
    # ### end Alembic commands ###
