"""add_trialcommodity_applytime

Revision ID: ac5192fdd476
Revises: 6d2d45a716f5
Create Date: 2018-12-21 15:44:31.847054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac5192fdd476'
down_revision = '6d2d45a716f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('GuessNumAward', 'SUid',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.add_column('TrialCommodity', sa.Column('AgreeEndTime', sa.Date(), nullable=True))
    op.add_column('TrialCommodity', sa.Column('AgreeStartTime', sa.Date(), nullable=True))
    op.add_column('TrialCommodity', sa.Column('ApplyEndTime', sa.DateTime(), nullable=False))
    op.add_column('TrialCommodity', sa.Column('ApplyStartTime', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TrialCommodity', 'ApplyStartTime')
    op.drop_column('TrialCommodity', 'ApplyEndTime')
    op.drop_column('TrialCommodity', 'AgreeStartTime')
    op.drop_column('TrialCommodity', 'AgreeEndTime')
    op.alter_column('GuessNumAward', 'SUid',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
