"""droped_a_table

Revision ID: ac58b9829363
Revises: 01ba748a96b0
Create Date: 2019-04-26 03:15:41.416354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac58b9829363'
down_revision = '01ba748a96b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserNewsCategory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserNewsCategory',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('UNC', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('NSCid', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('USid', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('UNCsort', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('UNC'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
