"""关于佣金的字段

Revision ID: aeadee3b5044
Revises: 2f9fa3b6ddec
Create Date: 2018-12-29 10:57:35.527674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeadee3b5044'
down_revision = '2f9fa3b6ddec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Commision',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('COid', sa.String(length=64), nullable=False),
    sa.Column('Levelcommision', sa.String(length=32), nullable=True),
    sa.Column('InviteNum', sa.Integer(), nullable=True),
    sa.Column('GroupSale', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('PesonalSale', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('InviteNumScale', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('GroupSaleScale', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('PesonalSaleScale', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('ReduceRatio', sa.String(length=32), nullable=True),
    sa.Column('IncreaseRatio', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('COid')
    )
    op.add_column('OrderPart', sa.Column('UPperid3', sa.String(length=64), nullable=True))
    op.add_column('OrderPart', sa.Column('USCommission3', sa.Float(), nullable=True))
    op.add_column('User', sa.Column('CommisionLevel', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'CommisionLevel')
    op.drop_column('OrderPart', 'USCommission3')
    op.drop_column('OrderPart', 'UPperid3')
    op.drop_table('Commision')
    # ### end Alembic commands ###
