"""'add'

Revision ID: aff0f00096e3
Revises: c9bc6223eacf
Create Date: 2019-04-09 13:51:42.397066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aff0f00096e3'
down_revision = 'c9bc6223eacf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TimeLimitedSku',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('TLSid', sa.String(length=64), nullable=False),
    sa.Column('TLPid', sa.String(length=64), nullable=True),
    sa.Column('TLSstock', sa.String(length=64), nullable=True),
    sa.Column('SKUid', sa.String(length=64), nullable=True),
    sa.Column('SKUprice', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('TLSid')
    )
    op.drop_table('time_limited_sku')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_limited_sku',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('TLSid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('TLPid', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('TLSstock', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('SKUid', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('SKUprice', mysql.DECIMAL(precision=28, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('TLSid'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('TimeLimitedSku')
    # ### end Alembic commands ###
