"""mixed_pay

Revision ID: b0e77aa1e884
Revises: 454bbe682c11
Create Date: 2019-04-24 11:52:44.402345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e77aa1e884'
down_revision = '454bbe682c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderMain', sa.Column('OMintegralpayed', sa.Integer(), nullable=True))
    op.add_column('ProductBrand', sa.Column('PBintegralPayRate', sa.Integer(), nullable=True))
    op.add_column('SupplizerDepositLog', sa.Column('SDLcontentid', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SupplizerDepositLog', 'SDLcontentid')
    op.drop_column('ProductBrand', 'PBintegralPayRate')
    op.drop_column('OrderMain', 'OMintegralpayed')
    # ### end Alembic commands ###
