"""add_some_rufuse_reason

Revision ID: b21c819f6453
Revises: 2e501f910972
Create Date: 2019-01-02 19:46:42.112157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21c819f6453'
down_revision = '2e501f910972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('News', sa.Column('NEfrom', sa.Integer(), nullable=True))
    op.add_column('News', sa.Column('NErefusereason', sa.String(length=125), nullable=True))
    op.add_column('TrialCommodity', sa.Column('TCrejectReason', sa.String(length=125), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TrialCommodity', 'TCrejectReason')
    op.drop_column('News', 'NErefusereason')
    op.drop_column('News', 'NEfrom')
    # ### end Alembic commands ###
