"""Supplizer_address

Revision ID: b7c0e30b2843
Revises: 659a62e03c5f
Create Date: 2019-01-10 16:53:55.869417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c0e30b2843'
down_revision = '659a62e03c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserAddress', sa.Column('UAFrom', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserAddress', 'UAFrom')
    # ### end Alembic commands ###
