"""订单上级字段改到副单中

Revision ID: b7cf821a7c3d
Revises: 2903d42872f9
Create Date: 2018-12-11 21:10:02.384882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7cf821a7c3d'
down_revision = '2903d42872f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderMain', 'UPperid')
    op.drop_column('OrderMain', 'UPperid2')
    op.drop_column('OrderMain', 'OMtotalCommision')
    op.add_column('OrderPart', sa.Column('UPperid', sa.String(length=64), nullable=True))
    op.add_column('OrderPart', sa.Column('UPperid2', sa.String(length=64), nullable=True))
    op.add_column('OrderPart', sa.Column('USCommission1', sa.Float(), nullable=True))
    op.add_column('OrderPart', sa.Column('USCommission2', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderPart', 'USCommission2')
    op.drop_column('OrderPart', 'USCommission1')
    op.drop_column('OrderPart', 'UPperid2')
    op.drop_column('OrderPart', 'UPperid')
    op.add_column('OrderMain', sa.Column('OMtotalCommision', mysql.FLOAT(), nullable=True))
    op.add_column('OrderMain', sa.Column('UPperid2', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True))
    op.add_column('OrderMain', sa.Column('UPperid', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True))
    # ### end Alembic commands ###
