"""'add'

Revision ID: b8c49e5235d4
Revises: b7c0e30b2843
Create Date: 2019-01-10 17:51:18.650612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8c49e5235d4'
down_revision = 'b7c0e30b2843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SupplizerAccount', sa.Column('SUid', sa.String(length=64), nullable=True))
    op.drop_column('SupplizerAccount', 'SPid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SupplizerAccount', sa.Column('SPid', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('SupplizerAccount', 'SUid')
    # ### end Alembic commands ###
