"""'add'

Revision ID: ba2398443bfb
Revises: e3a5a7647698
Create Date: 2019-02-25 17:01:43.138260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2398443bfb'
down_revision = 'e3a5a7647698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
