"""让利字段

Revision ID: bb60cb9d1c75
Revises: c38bcb2b4cf9
Create Date: 2019-01-08 23:13:46.916792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb60cb9d1c75'
down_revision = 'c38bcb2b4cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderPart', sa.Column('SkudevideRate', sa.DECIMAL(scale=2), nullable=True))
    op.add_column('ProductSku', sa.Column('SkudevideRate', sa.DECIMAL(scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ProductSku', 'SkudevideRate')
    op.drop_column('OrderPart', 'SkudevideRate')
    # ### end Alembic commands ###
