"""售后信息

Revision ID: bbad4c7677e1
Revises: 11baa3b41e64
Create Date: 2019-01-09 22:43:35.845890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbad4c7677e1'
down_revision = '11baa3b41e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrderRefundNotes',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ORNid', sa.String(length=64), nullable=False),
    sa.Column('OMid', sa.String(length=64), nullable=True),
    sa.Column('OPid', sa.String(length=64), nullable=True),
    sa.Column('UserName', sa.String(length=32), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('ORNaction', sa.Integer(), nullable=True),
    sa.Column('ORNabo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ORNid')
    )
    op.create_index(op.f('ix_OrderRefundNotes_OMid'), 'OrderRefundNotes', ['OMid'], unique=False)
    op.create_index(op.f('ix_OrderRefundNotes_OPid'), 'OrderRefundNotes', ['OPid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_OrderRefundNotes_OPid'), table_name='OrderRefundNotes')
    op.drop_index(op.f('ix_OrderRefundNotes_OMid'), table_name='OrderRefundNotes')
    op.drop_table('OrderRefundNotes')
    # ### end Alembic commands ###
