"""佣金设置

Revision ID: bca6dfffc4ef
Revises: 72d56935126b
Create Date: 2018-12-28 19:45:15.414357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca6dfffc4ef'
down_revision = '72d56935126b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('USCommission3', sa.Float(), nullable=True))
    op.add_column('User', sa.Column('USsupper3', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'USsupper3')
    op.drop_column('User', 'USCommission3')
    # ### end Alembic commands ###
