"""IntegralStore

Revision ID: bcc562167299
Revises: 8a632562cfa6
Create Date: 2019-04-21 19:36:43.275185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc562167299'
down_revision = '8a632562cfa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IntegralProduct',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('IPid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=False),
    sa.Column('IPfrom', sa.Integer(), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=True),
    sa.Column('IPrejectReason', sa.String(length=255), nullable=True),
    sa.Column('IPstatus', sa.Integer(), nullable=True),
    sa.Column('IPprice', sa.BIGINT(), nullable=True),
    sa.Column('IPsaleVolume', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('IPid')
    )
    op.create_table('IntegralProductSku',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('IPSid', sa.String(length=64), nullable=False),
    sa.Column('IPid', sa.String(length=64), nullable=False),
    sa.Column('IPSstock', sa.BIGINT(), nullable=True),
    sa.Column('SKUid', sa.String(length=64), nullable=True),
    sa.Column('SKUprice', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('IPSid')
    )
    op.add_column('UserSignIn', sa.Column('OPayno', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserSignIn', 'OPayno')
    op.drop_table('IntegralProductSku')
    op.drop_table('IntegralProduct')
    # ### end Alembic commands ###
