"""订单优惠券

Revision ID: bcc5cd975099
Revises: 5e296d2991ae
Create Date: 2018-11-19 20:17:31.240017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcc5cd975099'
down_revision = '5e296d2991ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderRaward', sa.Column('COid', sa.String(length=64), nullable=False))
    op.add_column('OrderRaward', sa.Column('OMid', sa.String(length=64), nullable=False))
    op.drop_column('OrderRaward', 'OCnum')
    op.drop_column('OrderRaward', 'CPid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderRaward', sa.Column('CPid', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False))
    op.add_column('OrderRaward', sa.Column('OCnum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('OrderRaward', 'OMid')
    op.drop_column('OrderRaward', 'COid')
    # ### end Alembic commands ###
