"""佣金计算

Revision ID: beeef33e976c
Revises: 4125e69d372b
Create Date: 2018-11-16 13:21:00.194454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'beeef33e976c'
down_revision = '4125e69d372b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderMain', sa.Column('OMtotalCommision', sa.Float(), nullable=True))
    op.drop_column('OrderMain', 'PRfrom')
    op.add_column('OrderPart', sa.Column('PRcreateId', sa.String(length=64), nullable=True))
    op.add_column('OrderPart', sa.Column('PRfrom', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderPart', 'PRfrom')
    op.drop_column('OrderPart', 'PRcreateId')
    op.add_column('OrderMain', sa.Column('PRfrom', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('OrderMain', 'OMtotalCommision')
    # ### end Alembic commands ###
