"""快递自增字段

Revision ID: c00045b9953a
Revises: cdbcad239210
Create Date: 2018-11-12 18:27:29.737111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00045b9953a'
down_revision = 'cdbcad239210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
