"""仓库初始表

Revision ID: c0ac37fe9386
Revises: 01528670f7ad
Create Date: 2018-11-21 16:07:57.098434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0ac37fe9386'
down_revision = '01528670f7ad'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Supplizer',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SUid', sa.String(length=64), nullable=False),
    sa.Column('SUname', sa.String(length=16), nullable=False),
    sa.Column('SUlinkman', sa.String(length=16), nullable=False),
    sa.Column('SUlinkPhone', sa.String(length=11), nullable=False),
    sa.Column('SUaddress', sa.String(length=255), nullable=False),
    sa.Column('SUstatus', sa.Integer(), nullable=True),
    sa.Column('SUisseller', sa.Boolean(), nullable=True),
    sa.Column('SUbank', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('SUid')
    )
    op.create_table('SupplizerProduct',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SPid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('SPid')
    )
    op.create_index(op.f('ix_SupplizerProduct_PRid'), 'SupplizerProduct', ['PRid'], unique=False)
    op.create_table('ware_house_in_flow',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('WHIFid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=False),
    sa.Column('PRnum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('WHIFid')
    )
    op.create_table('ware_house_product',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('WHPid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('WAid', sa.String(length=64), nullable=False),
    sa.Column('PRnum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('WHPid')
    )
    op.drop_table('WareHouseFlowing')
    op.drop_table('supplizer')
    op.alter_column('OrderRefund', 'OPid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=True)
    op.add_column('WareHouse', sa.Column('WAaddress', sa.String(length=64), nullable=False))
    op.add_column('WareHouse', sa.Column('WAcontact', sa.String(length=16), nullable=False))
    op.add_column('WareHouse', sa.Column('WAname', sa.String(length=32), nullable=False))
    op.add_column('WareHouse', sa.Column('WAphone', sa.String(length=11), nullable=False))
    op.add_column('WareHouse', sa.Column('WAstatus', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('WareHouse', 'WAstatus')
    op.drop_column('WareHouse', 'WAphone')
    op.drop_column('WareHouse', 'WAname')
    op.drop_column('WareHouse', 'WAcontact')
    op.drop_column('WareHouse', 'WAaddress')
    op.alter_column('OrderRefund', 'OPid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=True)
    op.create_table('supplizer',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('SUid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('SUname', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('SUlinkman', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('SUlinkPhone', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('SUaddress', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('SUstatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('SUid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('WareHouseFlowing',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('WHFkd', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('WHFkd'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('ware_house_product')
    op.drop_table('ware_house_in_flow')
    op.drop_index(op.f('ix_SupplizerProduct_PRid'), table_name='SupplizerProduct')
    op.drop_table('SupplizerProduct')
    op.drop_table('Supplizer')
    # ### end Alembic commands ###
