"""品牌供应商

Revision ID: c13345b8f1e9
Revises: 57354c064ced
Create Date: 2018-12-19 10:34:53.462896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13345b8f1e9'
down_revision = '57354c064ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProductBrand', sa.Column('SUid', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ProductBrand', 'SUid')
    # ### end Alembic commands ###
