"""'add'

Revision ID: c1a3e4f38453
Revises: 4316ba9e2b97
Create Date: 2019-02-19 05:02:33.339561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1a3e4f38453'
down_revision = '4316ba9e2b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ActivationCodeRule', sa.Column('ACRcash', sa.DECIMAL(), nullable=True))
    op.add_column('ActivationCodeRule', sa.Column('ACRnum', sa.Integer(), nullable=True))
    op.alter_column('ProductSku', 'SKUsn',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ProductSku', 'SKUsn',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=True)
    op.drop_column('ActivationCodeRule', 'ACRnum')
    op.drop_column('ActivationCodeRule', 'ACRcash')
    # ### end Alembic commands ###
