"""'add'

Revision ID: c335a587fdfd
Revises: 65f6da28d07c
Create Date: 2018-11-30 22:19:55.707940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c335a587fdfd'
down_revision = '65f6da28d07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Answer',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('QAid', sa.String(length=64), nullable=False),
    sa.Column('QUid', sa.String(length=64), nullable=True),
    sa.Column('QAcontent', sa.Text(), nullable=True),
    sa.Column('QAcreateId', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('QAid')
    )
    op.create_table('AnswerUser',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('QAUid', sa.String(length=64), nullable=False),
    sa.Column('QAid', sa.String(length=64), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('QAUid')
    )
    op.create_table('Quest',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('QUid', sa.String(length=64), nullable=False),
    sa.Column('QOid', sa.String(length=64), nullable=True),
    sa.Column('QUquest', sa.Text(), nullable=True),
    sa.Column('QUcreateId', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('QUid')
    )
    op.create_table('QuestOutline',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('QOid', sa.String(length=64), nullable=False),
    sa.Column('QOicon', sa.Text(), nullable=True),
    sa.Column('QOname', sa.Text(), nullable=True),
    sa.Column('QOcreateId', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('QOid')
    )
    op.add_column('Admin', sa.Column('ADnum', sa.Integer(), autoincrement=True, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Admin', 'ADnum')
    op.drop_table('QuestOutline')
    op.drop_table('Quest')
    op.drop_table('AnswerUser')
    op.drop_table('Answer')
    # ### end Alembic commands ###
