"""'add'

Revision ID: c38bcb2b4cf9
Revises: 5233dd0ace6b
Create Date: 2019-01-08 22:00:40.107481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38bcb2b4cf9'
down_revision = '5233dd0ace6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SignInAward', sa.Column('SIAday', sa.Integer(), nullable=True))
    op.add_column('SignInAward', sa.Column('SIAnum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SignInAward', 'SIAnum')
    op.drop_column('SignInAward', 'SIAday')
    # ### end Alembic commands ###
