"""活动库存

Revision ID: c61af4aa5626
Revises: 661df4a133ac
Create Date: 2019-01-08 10:56:26.642247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c61af4aa5626'
down_revision = '661df4a133ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OutStock',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OSid', sa.String(length=64), nullable=False),
    sa.Column('SKUid', sa.String(length=64), nullable=False),
    sa.Column('OSnum', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('OSid')
    )
    op.add_column('MagicBoxApply', sa.Column('OSid', sa.String(length=64), nullable=True))
    op.drop_column('MagicBoxApply', 'SKUstock')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MagicBoxApply', sa.Column('SKUstock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('MagicBoxApply', 'OSid')
    op.drop_table('OutStock')
    # ### end Alembic commands ###
