"""'add'

Revision ID: c83598451ba0
Revises: cbe1d20d7b8c
Create Date: 2018-12-05 21:17:40.075294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83598451ba0'
down_revision = 'cbe1d20d7b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserWallet',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UWid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('UWbalance', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('UWtotal', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('UWid')
    )
    op.add_column('UserCommission', sa.Column('OPid', sa.String(length=64), nullable=True))
    op.add_column('UserCommission', sa.Column('PRtitle', sa.String(length=255), nullable=True))
    op.add_column('UserCommission', sa.Column('SKUpic', sa.Text(), nullable=True))
    op.add_column('UserCommission', sa.Column('UCendTime', sa.DateTime(), nullable=True))
    op.add_column('UserCommission', sa.Column('UCtype', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserCommission', 'UCtype')
    op.drop_column('UserCommission', 'UCendTime')
    op.drop_column('UserCommission', 'SKUpic')
    op.drop_column('UserCommission', 'PRtitle')
    op.drop_column('UserCommission', 'OPid')
    op.drop_table('UserWallet')
    # ### end Alembic commands ###
