"""'add'

Revision ID: c9bc6223eacf
Revises: 442d560ee00f
Create Date: 2019-04-09 13:50:27.001524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9bc6223eacf'
down_revision = '442d560ee00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TimeLimitedApply',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('TLAid', sa.String(length=64), nullable=False),
    sa.Column('TLAstartTime', sa.DateTime(), nullable=True),
    sa.Column('TLAendTime', sa.DateTime(), nullable=True),
    sa.Column('TLAstatus', sa.Integer(), nullable=True),
    sa.Column('ADid', sa.String(length=64), nullable=True),
    sa.Column('TLAtopPic', sa.Text(), nullable=True),
    sa.Column('TlAname', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('TLAid')
    )
    op.create_table('TimeLimitedProduct',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('TLPid', sa.String(length=64), nullable=False),
    sa.Column('TLAid', sa.String(length=64), nullable=True),
    sa.Column('TLAfrom', sa.Integer(), nullable=True),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=True),
    sa.Column('TLArejectReson', sa.String(length=255), nullable=True),
    sa.Column('TLAstatus', sa.Integer(), nullable=True),
    sa.Column('PRmainpic', sa.String(length=255), nullable=False),
    sa.Column('PRtitle', sa.String(length=255), nullable=False),
    sa.Column('PBid', sa.String(length=64), nullable=False),
    sa.Column('PBname', sa.String(length=64), nullable=False),
    sa.Column('PRattribute', sa.String(length=255), nullable=True),
    sa.Column('PRdescription', sa.Text(), nullable=True),
    sa.Column('PRfeight', sa.Float(), nullable=True),
    sa.Column('PRprice', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('TLPid')
    )
    op.create_table('time_limited_sku',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('TLSid', sa.String(length=64), nullable=False),
    sa.Column('TLPid', sa.String(length=64), nullable=True),
    sa.Column('TLSstock', sa.String(length=64), nullable=True),
    sa.Column('SKUid', sa.String(length=64), nullable=True),
    sa.Column('SKUprice', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('TLSid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_limited_sku')
    op.drop_table('TimeLimitedProduct')
    op.drop_table('TimeLimitedApply')
    # ### end Alembic commands ###
