"""物流使用text

Revision ID: cb0a9dfe00d4
Revises: 3acfc68d3192
Create Date: 2018-11-18 20:20:40.751230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0a9dfe00d4'
down_revision = '3acfc68d3192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
