"""快递自增字段

Revision ID: cdbcad239210
Revises: 6e102472ae2d
Create Date: 2018-11-12 18:21:28.554856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbcad239210'
down_revision = '6e102472ae2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
