"""add column for coupon

Revision ID: cdf1018a832a
Revises: 6748e99cc2f8
Create Date: 2018-12-30 19:52:20.742311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf1018a832a'
down_revision = '6748e99cc2f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Coupon', sa.Column('ADid', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Coupon', 'ADid')
    # ### end Alembic commands ###
