"""字段拼写错误

Revision ID: d6c789595c6d
Revises: 724fc23e13ff
Create Date: 2018-11-15 11:45:53.055771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6c789595c6d'
down_revision = '724fc23e13ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Coupon', sa.Column('COvalidEndTime', sa.DateTime(), nullable=True))
    op.drop_column('Coupon', 'COvalidEndTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Coupon', sa.Column('COvalidEndTime', mysql.DATETIME(), nullable=True))
    op.drop_column('Coupon', 'COvalidEndTime')
    # ### end Alembic commands ###
