"""'modify_news_video'

Revision ID: d96916bb8d72
Revises: 9770a0c9c59f
Create Date: 2018-11-14 14:40:57.853073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96916bb8d72'
down_revision = '9770a0c9c59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NewsVideo', sa.Column('NVduration', sa.Float(precision=6), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NewsVideo', 'NVduration')
    # ### end Alembic commands ###
