"""付款详情

Revision ID: daed9a4ea3d2
Revises: b69247d8f473
Create Date: 2018-11-05 09:47:45.377861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daed9a4ea3d2'
down_revision = 'b69247d8f473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderPay', sa.Column('OPaybody', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderPay', 'OPaybody')
    # ### end Alembic commands ###
