"""新人参与记录

Revision ID: dcf3926400e6
Revises: 32112ca8af58
Create Date: 2018-12-10 14:04:52.883108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf3926400e6'
down_revision = '32112ca8af58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FreshManJoinFlow',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('FMJFid', sa.String(length=64), nullable=False),
    sa.Column('OMid', sa.String(length=64), nullable=False),
    sa.Column('UPid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('FMJFid')
    )
    op.add_column('FreshManFirstProduct', sa.Column('PBname', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FreshManFirstProduct', 'PBname')
    op.drop_table('FreshManJoinFlow')
    # ### end Alembic commands ###
