"""魔盒库存调整

Revision ID: dd69e5d45ee7
Revises: 5ab0f8b34e54
Create Date: 2019-01-09 00:49:12.052046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd69e5d45ee7'
down_revision = '5ab0f8b34e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GuessNumAward', sa.Column('OSid', sa.String(length=64), nullable=True))
    op.drop_column('GuessNumAward', 'SKUstock')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GuessNumAward', sa.Column('SKUstock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('GuessNumAward', 'OSid')
    # ### end Alembic commands ###
