"""售后类型

Revision ID: e0fc212867b0
Revises: 4ecd65279905
Create Date: 2018-11-20 20:17:08.634242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0fc212867b0'
down_revision = '4ecd65279905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DisputeType',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('DIid', sa.String(length=64), nullable=False),
    sa.Column('DIname', sa.String(length=32), nullable=False),
    sa.Column('DIsort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('DIid')
    )
    op.create_table('WareHouse',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('WAid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('WAid')
    )
    op.create_table('WareHouseFlowing',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('WHFkd', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('WHFkd')
    )
    op.create_table('supplizer',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SUid', sa.String(length=64), nullable=False),
    sa.Column('SUname', sa.String(length=16), nullable=False),
    sa.Column('SUlinkman', sa.String(length=16), nullable=False),
    sa.Column('SUlinkPhone', sa.String(length=11), nullable=False),
    sa.Column('SUaddress', sa.String(length=255), nullable=False),
    sa.Column('SUstatus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('SUid')
    )
    op.add_column('OrderRefund', sa.Column('ORAid', sa.String(length=64), nullable=False))
    op.add_column('OrderRefund', sa.Column('ORrecvaddress', sa.String(length=255), nullable=False))
    op.add_column('OrderRefund', sa.Column('ORrecvname', sa.String(length=16), nullable=False))
    op.add_column('OrderRefund', sa.Column('ORrecvphone', sa.String(length=11), nullable=False))
    op.alter_column('OrderRefundApply', 'OPid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('OrderRefundApply', 'OPid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=False)
    op.drop_column('OrderRefund', 'ORrecvphone')
    op.drop_column('OrderRefund', 'ORrecvname')
    op.drop_column('OrderRefund', 'ORrecvaddress')
    op.drop_column('OrderRefund', 'ORAid')
    op.drop_table('supplizer')
    op.drop_table('WareHouseFlowing')
    op.drop_table('WareHouse')
    op.drop_table('DisputeType')
    # ### end Alembic commands ###
