"""标签修改

Revision ID: e715f346ce47
Revises: 96e182e8f6d9
Create Date: 2018-11-21 18:40:38.795014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e715f346ce47'
down_revision = '96e182e8f6d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Items', sa.Column('ITauthority', sa.Integer(), nullable=True))
    op.add_column('Items', sa.Column('ITposition', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Items', 'ITposition')
    op.drop_column('Items', 'ITauthority')
    # ### end Alembic commands ###
