"""新人首单model

Revision ID: e922800747e2
Revises: 52c66d37221b
Create Date: 2018-12-07 09:31:21.028953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e922800747e2'
down_revision = '52c66d37221b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FreshManFirstProduct', 'PRdescription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FreshManFirstProduct', sa.Column('PRdescription', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
