"""申请的字段

Revision ID: e93b65883580
Revises: 258a7a698576
Create Date: 2018-12-13 13:53:21.931563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e93b65883580'
down_revision = '258a7a698576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ActivationCodeApply', sa.Column('ACAbankSn', sa.String(length=32), nullable=False))
    op.add_column('ActivationCodeApply', sa.Column('ACAbankname', sa.String(length=125), nullable=False))
    op.add_column('ActivationCodeApply', sa.Column('ACAname', sa.String(length=32), nullable=False))
    op.drop_column('ActivationCodeApply', 'ACRbankAddress')
    op.drop_column('ActivationCodeApply', 'ACRbankSn')
    op.drop_column('ActivationCodeApply', 'ACRname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ActivationCodeApply', sa.Column('ACRname', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('ActivationCodeApply', sa.Column('ACRbankSn', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('ActivationCodeApply', sa.Column('ACRbankAddress', mysql.VARCHAR(length=125), nullable=False))
    op.drop_column('ActivationCodeApply', 'ACAname')
    op.drop_column('ActivationCodeApply', 'ACAbankname')
    op.drop_column('ActivationCodeApply', 'ACAbankSn')
    # ### end Alembic commands ###
