"""'add'

Revision ID: efb958e7178c
Revises: 8fb0a7a8846f
Create Date: 2019-03-22 17:37:28.593627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb958e7178c'
down_revision = '8fb0a7a8846f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CompanyMessage', sa.Column('CMreadnum', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CompanyMessage', 'CMreadnum')
    # ### end Alembic commands ###
