"""帮车模和状态

Revision ID: f1c503ed1cf7
Revises: c83598451ba0
Create Date: 2018-12-06 10:30:30.425436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c503ed1cf7'
down_revision = 'c83598451ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MagicBoxJoin', sa.Column('MBJstatus', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MagicBoxJoin', 'MBJstatus')
    # ### end Alembic commands ###
