"""猜数字奖励设置

Revision ID: f1e3cbd2fe31
Revises: c21685879c11
Create Date: 2018-11-28 10:13:11.347013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1e3cbd2fe31'
down_revision = 'c21685879c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GuessNumAward',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('GNAAid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=False),
    sa.Column('SKUid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('GNAAstarttime', sa.Date(), nullable=False),
    sa.Column('GNAAendtime', sa.Date(), nullable=False),
    sa.Column('SKUprice', sa.Float(), nullable=False),
    sa.Column('GNAAstatus', sa.Integer(), nullable=True),
    sa.Column('AgreeStartime', sa.Date(), nullable=True),
    sa.Column('AgreeEndtime', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('GNAAid')
    )
    op.drop_column('CorrectNum', 'SKUid')
    op.add_column('GuessNum', sa.Column('PRid', sa.String(length=64), nullable=False))
    op.add_column('GuessNum', sa.Column('SKUid', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GuessNum', 'SKUid')
    op.drop_column('GuessNum', 'PRid')
    op.add_column('CorrectNum', sa.Column('SKUid', mysql.VARCHAR(length=64), nullable=False))
    op.drop_table('GuessNumAward')
    # ### end Alembic commands ###
