"""index

Revision ID: f253540e29c4
Revises: 2fa61d4d0a32
Create Date: 2018-11-12 13:14:01.628953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f253540e29c4'
down_revision = '2fa61d4d0a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IndexBrand',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('IBid', sa.String(length=64), nullable=False),
    sa.Column('PBid', sa.String(length=64), nullable=False),
    sa.Column('IBsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('IBid')
    )
    op.create_table('IndexBrandProduct',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('IBPid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('IBPsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('IBPid', 'PRid')
    )
    op.drop_table('IndexProductBrand')
    op.drop_table('IndexProductBrandItem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IndexProductBrandItem',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('IPBIid', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('PRid', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('IPBIsort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('IPBIid', 'PRid'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('IndexProductBrand',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('IPBid', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('PBid', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('IPBsort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('IPBid'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('IndexBrandProduct')
    op.drop_table('IndexBrand')
    # ### end Alembic commands ###
