"""'add'

Revision ID: f39363d7b427
Revises: 8b2cf082e550
Create Date: 2019-04-17 22:07:13.393636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39363d7b427'
down_revision = '8b2cf082e550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
