"""add_admin

Revision ID: f3cbc5760c0b
Revises: fa474cdc0c54
Create Date: 2019-05-15 16:42:39.638607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3cbc5760c0b'
down_revision = 'fa474cdc0c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AdminAction',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('AAid', sa.String(length=64), nullable=False),
    sa.Column('ADid', sa.String(length=64), nullable=True),
    sa.Column('AAaction', sa.Integer(), nullable=True),
    sa.Column('AAmodel', sa.String(length=255), nullable=True),
    sa.Column('AAdetail', mysql.LONGTEXT(), nullable=True),
    sa.Column('AAkey', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('AAid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AdminAction')
    # ### end Alembic commands ###
