"""add

Revision ID: f46fc25a66b5
Revises: 
Create Date: 2019-04-17 15:55:48.082618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f46fc25a66b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ActivationCodeApply',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ACAid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('ACAname', sa.String(length=32), nullable=False),
    sa.Column('ACAbankSn', sa.String(length=32), nullable=False),
    sa.Column('ACAbankname', sa.String(length=125), nullable=False),
    sa.Column('ACAvouchers', sa.Text(), nullable=True),
    sa.Column('ACAapplyStatus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ACAid')
    )
    op.create_table('ActivationCodeRule',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ACRid', sa.String(length=64), nullable=False),
    sa.Column('ACRrule', sa.Text(), nullable=True),
    sa.Column('ACRphone', sa.String(length=32), nullable=True),
    sa.Column('ACRaddress', sa.String(length=64), nullable=True),
    sa.Column('ACRname', sa.String(length=16), nullable=False),
    sa.Column('ACRbankSn', sa.String(length=32), nullable=False),
    sa.Column('ACRbankAddress', sa.String(length=125), nullable=False),
    sa.Column('ACRAgreeMent', sa.Text(), nullable=True),
    sa.Column('ACRisShow', sa.Boolean(), nullable=True),
    sa.Column('ACRnum', sa.Integer(), nullable=True),
    sa.Column('ACRcash', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('ACRid')
    )
    op.create_table('Activity',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ACid', sa.Integer(), nullable=False),
    sa.Column('ACbackGround', sa.String(length=255), nullable=False),
    sa.Column('ACtopPic', sa.String(length=255), nullable=False),
    sa.Column('ACbutton', sa.String(length=16), nullable=True),
    sa.Column('ACtype', sa.Integer(), nullable=True),
    sa.Column('ACshow', sa.Boolean(), nullable=True),
    sa.Column('ACdesc', sa.Text(), nullable=True),
    sa.Column('ACname', sa.String(length=16), nullable=False),
    sa.Column('ACsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ACid')
    )
    op.create_index(op.f('ix_Activity_ACtype'), 'Activity', ['ACtype'], unique=True)
    op.create_table('AddressArea',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('AAid', sa.String(length=8), nullable=False),
    sa.Column('AAname', sa.String(length=32), nullable=False),
    sa.Column('ACid', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('AAid')
    )
    op.create_table('AddressCity',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ACid', sa.String(length=8), nullable=False),
    sa.Column('ACname', sa.String(length=20), nullable=False),
    sa.Column('APid', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('ACid')
    )
    op.create_table('AddressProvince',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('APid', sa.String(length=8), nullable=False),
    sa.Column('APname', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('APid')
    )
    op.create_table('Admin',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ADid', sa.String(length=64), nullable=False),
    sa.Column('ADnum', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('ADname', sa.String(length=255), nullable=True),
    sa.Column('ADtelphone', sa.String(length=13), nullable=True),
    sa.Column('ADpassword', sa.Text(), nullable=False),
    sa.Column('ADfirstpwd', sa.Text(), nullable=True),
    sa.Column('ADfirstname', sa.Text(), nullable=True),
    sa.Column('ADheader', sa.Text(), nullable=True),
    sa.Column('ADlevel', sa.Integer(), nullable=True),
    sa.Column('ADstatus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ADid')
    )
    op.create_table('AdminNotes',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ANid', sa.String(length=64), nullable=False),
    sa.Column('ADid', sa.String(length=64), nullable=False),
    sa.Column('ANaction', sa.Text(), nullable=True),
    sa.Column('ANdoneid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ANid')
    )
    op.create_table('AdminPermission',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ADPid', sa.String(length=64), nullable=False),
    sa.Column('ADid', sa.String(length=64), nullable=True),
    sa.Column('PIid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ADPid')
    )
    op.create_table('Answer',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('QAid', sa.String(length=64), nullable=False),
    sa.Column('QUid', sa.String(length=64), nullable=True),
    sa.Column('QAcontent', sa.Text(), nullable=True),
    sa.Column('QAcreateId', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('QAid')
    )
    op.create_table('AnswerUser',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('QAUid', sa.String(length=64), nullable=False),
    sa.Column('QAid', sa.String(length=64), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('QAUid')
    )
    op.create_table('Approval',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('AVid', sa.String(length=64), nullable=False),
    sa.Column('AVname', sa.String(length=255), nullable=False),
    sa.Column('AVstartid', sa.String(length=64), nullable=False),
    sa.Column('AVlevel', sa.Integer(), nullable=True),
    sa.Column('AVstatus', sa.Integer(), nullable=True),
    sa.Column('AVcontent', sa.String(length=64), nullable=True),
    sa.Column('PTid', sa.String(length=64), nullable=True),
    sa.Column('AVcontentdetail', mysql.LONGTEXT(), nullable=True),
    sa.Column('AVstartdetail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('AVid')
    )
    op.create_table('ApprovalNotes',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ANid', sa.String(length=64), nullable=False),
    sa.Column('AVid', sa.String(length=64), nullable=True),
    sa.Column('AVadname', sa.Text(), nullable=True),
    sa.Column('ADid', sa.String(length=64), nullable=True),
    sa.Column('ANaction', sa.Integer(), nullable=True),
    sa.Column('ANabo', sa.Text(), nullable=True),
    sa.Column('ANfrom', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ANid')
    )
    op.create_table('BrandwithItems',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('BWIid', sa.String(length=64), nullable=False),
    sa.Column('ITid', sa.String(length=64), nullable=False),
    sa.Column('PBid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('BWIid')
    )
    op.create_table('Carts',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('CAid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('SKUid', sa.String(length=64), nullable=False),
    sa.Column('CAnums', sa.Integer(), nullable=True),
    sa.Column('PBid', sa.String(length=64), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=True),
    sa.Column('CAfrom', sa.Integer(), nullable=True),
    sa.Column('Contentid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('CAid')
    )
    op.create_table('CashNotes',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('CNid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('CommisionFor', sa.Integer(), nullable=True),
    sa.Column('CNbankName', sa.Text(), nullable=True),
    sa.Column('CNbankDetail', sa.Text(), nullable=True),
    sa.Column('CNcardNo', sa.String(length=32), nullable=True),
    sa.Column('CNcashNum', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('CNcardName', sa.String(length=32), nullable=True),
    sa.Column('CNstatus', sa.Integer(), nullable=True),
    sa.Column('CNrejectReason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('CNid')
    )
    op.create_table('Commision',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('COid', sa.String(length=64), nullable=False),
    sa.Column('Levelcommision', sa.String(length=32), nullable=True),
    sa.Column('InviteNum', sa.Integer(), nullable=True),
    sa.Column('GroupSale', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('PesonalSale', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('InviteNumScale', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('GroupSaleScale', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('PesonalSaleScale', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('ReduceRatio', sa.String(length=32), nullable=True),
    sa.Column('IncreaseRatio', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('COid')
    )
    op.create_table('CompanyMessage',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('CMid', sa.String(length=64), nullable=False),
    sa.Column('CMtitle', sa.String(length=255), nullable=False),
    sa.Column('CMmessage', mysql.LONGTEXT(), nullable=False),
    sa.Column('CMindex', sa.Integer(), nullable=False),
    sa.Column('CMreadnum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('CMid')
    )
    op.create_table('CorrectNum',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('CNid', sa.String(length=64), nullable=False),
    sa.Column('CNnum', sa.String(length=16), nullable=False),
    sa.Column('CNdate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('CNid')
    )
    op.create_table('CounponHistory',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('CHid', sa.String(length=64), nullable=False),
    sa.Column('COid', sa.String(length=64), nullable=True),
    sa.Column('COcontent', sa.Text(), nullable=True),
    sa.Column('COaction', sa.Integer(), nullable=True),
    sa.Column('CHuser', sa.String(length=64), nullable=True),
    sa.Column('CHuserType', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('CHid')
    )
    op.create_table('Coupon',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('COid', sa.String(length=64), nullable=False),
    sa.Column('COname', sa.String(length=32), nullable=False),
    sa.Column('COisAvailable', sa.Boolean(), nullable=True),
    sa.Column('COcanCollect', sa.Boolean(), nullable=True),
    sa.Column('COcollectNum', sa.Integer(), nullable=True),
    sa.Column('COuseNum', sa.Integer(), nullable=True),
    sa.Column('COsendStarttime', sa.DateTime(), nullable=True),
    sa.Column('COsendEndtime', sa.DateTime(), nullable=True),
    sa.Column('COvalidStartTime', sa.DateTime(), nullable=True),
    sa.Column('COvalidEndTime', sa.DateTime(), nullable=True),
    sa.Column('COdiscount', sa.Float(), nullable=True),
    sa.Column('COdownLine', sa.Float(), nullable=True),
    sa.Column('COsubtration', sa.Float(), nullable=True),
    sa.Column('COdesc', sa.String(length=255), nullable=True),
    sa.Column('COlimitNum', sa.Integer(), nullable=True),
    sa.Column('COremainNum', sa.Integer(), nullable=True),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.Column('ADid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('COid')
    )
    op.create_table('CouponFor',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('CFid', sa.String(length=64), nullable=False),
    sa.Column('PCid', sa.String(length=64), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=True),
    sa.Column('PBid', sa.String(length=64), nullable=True),
    sa.Column('COid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('CFid')
    )
    op.create_table('CouponItem',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('CIid', sa.String(length=64), nullable=False),
    sa.Column('COid', sa.String(length=64), nullable=False),
    sa.Column('ITid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('CIid')
    )
    op.create_table('CouponUser',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UCid', sa.String(length=64), nullable=False),
    sa.Column('COid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('UCalreadyUse', sa.Boolean(), nullable=True),
    sa.Column('UCstatus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('UCid')
    )
    op.create_table('DisputeType',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('DIid', sa.String(length=64), nullable=False),
    sa.Column('DIname', sa.String(length=32), nullable=False),
    sa.Column('DIsort', sa.Integer(), nullable=False),
    sa.Column('DItype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('DIid')
    )
    op.create_table('FreshManFirstApply',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('FMFAid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=False),
    sa.Column('FMFAstartTime', sa.Date(), nullable=False),
    sa.Column('FMFAendTime', sa.Date(), nullable=False),
    sa.Column('FMFAfrom', sa.Integer(), nullable=True),
    sa.Column('FMFAstatus', sa.Integer(), nullable=True),
    sa.Column('ADid', sa.String(length=64), nullable=True),
    sa.Column('FMFArejectReson', sa.String(length=255), nullable=True),
    sa.Column('AgreeStartime', sa.Date(), nullable=True),
    sa.Column('AgreeEndtime', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('FMFAid', 'SUid')
    )
    op.create_table('FreshManFirstProduct',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('FMFPid', sa.String(length=64), nullable=False),
    sa.Column('FMFAid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('PRmainpic', sa.String(length=255), nullable=False),
    sa.Column('PRtitle', sa.String(length=255), nullable=False),
    sa.Column('PBid', sa.String(length=64), nullable=False),
    sa.Column('PBname', sa.String(length=64), nullable=False),
    sa.Column('PRattribute', sa.String(length=255), nullable=True),
    sa.Column('PRdescription', sa.Text(), nullable=True),
    sa.Column('PRfeight', sa.Float(), nullable=True),
    sa.Column('PRprice', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('FMFPid')
    )
    op.create_table('FreshManFirstSku',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('FMFSid', sa.String(length=64), nullable=False),
    sa.Column('FMFPid', sa.String(length=64), nullable=False),
    sa.Column('FMFPstock', sa.Integer(), nullable=True),
    sa.Column('SKUid', sa.String(length=64), nullable=False),
    sa.Column('SKUprice', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('FMFSid')
    )
    op.create_table('FreshManJoinFlow',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('FMJFid', sa.String(length=64), nullable=False),
    sa.Column('OMid', sa.String(length=64), nullable=False),
    sa.Column('OMprice', sa.Float(), nullable=False),
    sa.Column('UPid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('FMJFid')
    )
    op.create_table('GuessAwardFlow',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('GAFid', sa.String(length=64), nullable=False),
    sa.Column('GNid', sa.String(length=64), nullable=False),
    sa.Column('GAFstatus', sa.Integer(), nullable=True),
    sa.Column('OMid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('GAFid'),
    sa.UniqueConstraint('GNid')
    )
    op.create_table('GuessNum',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('GNid', sa.String(length=64), nullable=False),
    sa.Column('GNnum', sa.String(length=16), nullable=False),
    sa.Column('GNNAid', sa.String(length=64), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('GNdate', sa.Date(), nullable=True),
    sa.Column('SKUid', sa.String(length=64), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=True),
    sa.Column('Price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('GNid')
    )
    op.create_table('GuessNumAward',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('GNAAid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.Column('GNAAstarttime', sa.Date(), nullable=False),
    sa.Column('GNAAendtime', sa.Date(), nullable=False),
    sa.Column('GNAAfrom', sa.Integer(), nullable=True),
    sa.Column('GNAAstatus', sa.Integer(), nullable=True),
    sa.Column('ADid', sa.String(length=64), nullable=True),
    sa.Column('GNAArejectReason', sa.String(length=64), nullable=True),
    sa.Column('AgreeStartime', sa.Date(), nullable=True),
    sa.Column('AgreeEndtime', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('GNAAid')
    )
    op.create_table('GuessNumAwardProduct',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('GNAPid', sa.String(length=64), nullable=False),
    sa.Column('GNAAid', sa.String(length=64), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('PRmainpic', sa.String(length=255), nullable=False),
    sa.Column('PRtitle', sa.String(length=255), nullable=False),
    sa.Column('PBid', sa.String(length=64), nullable=False),
    sa.Column('PBname', sa.String(length=64), nullable=False),
    sa.Column('PRattribute', sa.String(length=255), nullable=True),
    sa.Column('PRdescription', sa.Text(), nullable=True),
    sa.Column('PRfeight', sa.Float(), nullable=True),
    sa.Column('PRprice', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('GNAPid')
    )
    op.create_table('GuessNumAwardSku',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('GNASid', sa.String(length=64), nullable=False),
    sa.Column('GNAPid', sa.String(length=64), nullable=True),
    sa.Column('SKUid', sa.String(length=64), nullable=False),
    sa.Column('SKUprice', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SKUstock', sa.Integer(), nullable=True),
    sa.Column('SKUdiscountone', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SKUdiscounttwo', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SKUdiscountthree', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SKUdiscountfour', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SKUdiscountfive', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SKUdiscountsix', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('GNASid')
    )
    op.create_table('IDcheck',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('IDCid', sa.String(length=64), nullable=False),
    sa.Column('IDCcode', sa.String(length=24), nullable=False),
    sa.Column('IDCname', sa.Text(), nullable=True),
    sa.Column('IDCresult', sa.Boolean(), nullable=True),
    sa.Column('IDCrealName', sa.Text(), nullable=True),
    sa.Column('IDCcardNo', sa.Text(), nullable=True),
    sa.Column('IDCaddrCode', sa.Text(), nullable=True),
    sa.Column('IDCbirth', sa.Text(), nullable=True),
    sa.Column('IDCsex', sa.Integer(), nullable=True),
    sa.Column('IDCcheckBit', sa.String(length=2), nullable=True),
    sa.Column('IDCaddr', sa.Text(), nullable=True),
    sa.Column('IDCerrorCode', sa.String(length=8), nullable=True),
    sa.Column('IDCreason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('IDCid')
    )
    op.create_table('IndexBanner',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('IBid', sa.String(length=64), nullable=False),
    sa.Column('IBpic', sa.String(length=255), nullable=False),
    sa.Column('IBsort', sa.Integer(), nullable=True),
    sa.Column('IBshow', sa.Boolean(), nullable=True),
    sa.Column('contentlink', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('IBid')
    )
    op.create_table('Items',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ITid', sa.String(length=64), nullable=False),
    sa.Column('ITname', sa.String(length=16), nullable=False),
    sa.Column('ITsort', sa.Integer(), nullable=True),
    sa.Column('ITdesc', sa.String(length=255), nullable=True),
    sa.Column('ITtype', sa.Integer(), nullable=True),
    sa.Column('ITrecommend', sa.Boolean(), nullable=True),
    sa.Column('ITauthority', sa.Integer(), nullable=True),
    sa.Column('ITposition', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ITid')
    )
    op.create_index(op.f('ix_Items_ITtype'), 'Items', ['ITtype'], unique=False)
    op.create_table('LogisticsCompnay',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LCname', sa.String(length=64), nullable=False),
    sa.Column('LCcode', sa.String(length=64), nullable=False),
    sa.Column('LCfirstCharater', sa.String(length=1), nullable=False),
    sa.Column('LCisCommon', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_LogisticsCompnay_LCcode'), 'LogisticsCompnay', ['LCcode'], unique=False)
    op.create_index(op.f('ix_LogisticsCompnay_LCfirstCharater'), 'LogisticsCompnay', ['LCfirstCharater'], unique=False)
    op.create_table('MagicBoxApply',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('MBAid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.Column('SKUid', sa.String(length=64), nullable=False),
    sa.Column('OSid', sa.String(length=64), nullable=True),
    sa.Column('MBAfrom', sa.Integer(), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('PBid', sa.String(length=64), nullable=False),
    sa.Column('MBAstarttime', sa.Date(), nullable=False),
    sa.Column('MBAendtime', sa.Date(), nullable=False),
    sa.Column('SKUprice', sa.Float(), nullable=False),
    sa.Column('SKUminPrice', sa.Float(), nullable=False),
    sa.Column('Gearsone', sa.String(length=64), nullable=False),
    sa.Column('Gearstwo', sa.String(length=64), nullable=False),
    sa.Column('Gearsthree', sa.String(length=64), nullable=False),
    sa.Column('MBAstatus', sa.Integer(), nullable=True),
    sa.Column('ADid', sa.String(length=64), nullable=True),
    sa.Column('MBArejectReason', sa.String(length=64), nullable=True),
    sa.Column('AgreeStartime', sa.Date(), nullable=True),
    sa.Column('AgreeEndtime', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('MBAid')
    )
    op.create_table('MagicBoxFlow',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('MBFid', sa.String(length=64), nullable=False),
    sa.Column('OMid', sa.String(length=64), nullable=False),
    sa.Column('MBJid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('MBFid')
    )
    op.create_table('MagicBoxJoin',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('MBJid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('MBAid', sa.String(length=64), nullable=False),
    sa.Column('MBJprice', sa.Float(), nullable=False),
    sa.Column('MBJstatus', sa.Integer(), nullable=True),
    sa.Column('MBJcurrentPrice', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('MBJid')
    )
    op.create_table('MagixBoxOpen',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('MBOid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('USname', sa.String(length=64), nullable=False),
    sa.Column('MBJid', sa.String(length=64), nullable=False),
    sa.Column('MBOgear', sa.Integer(), nullable=False),
    sa.Column('MBOresult', sa.Float(), nullable=False),
    sa.Column('MBOprice', sa.Float(), nullable=False),
    sa.Column('MBOhasShare', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('MBOid')
    )
    op.create_table('ManagerSystemNotes',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('MNid', sa.String(length=64), nullable=False),
    sa.Column('MNcontent', sa.Text(), nullable=True),
    sa.Column('MNstatus', sa.Integer(), nullable=True),
    sa.Column('MNcreateid', sa.String(length=64), nullable=True),
    sa.Column('MNupdateid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('MNid')
    )
    op.create_table('News',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('NEid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('USname', sa.String(length=128), nullable=True),
    sa.Column('USheader', sa.Text(), nullable=True),
    sa.Column('NEtitle', sa.String(length=128), nullable=False),
    sa.Column('NEtext', mysql.LONGTEXT(), nullable=True),
    sa.Column('NEstatus', sa.Integer(), nullable=True),
    sa.Column('NEpageviews', sa.Integer(), nullable=True),
    sa.Column('NEsource', sa.String(length=64), nullable=True),
    sa.Column('COid', sa.Text(), nullable=True),
    sa.Column('PRid', sa.Text(), nullable=True),
    sa.Column('NEmainpic', sa.String(length=255), nullable=True),
    sa.Column('NEfrom', sa.Integer(), nullable=True),
    sa.Column('NEisrecommend', sa.Boolean(), nullable=True),
    sa.Column('NErefusereason', sa.String(length=125), nullable=True),
    sa.PrimaryKeyConstraint('NEid')
    )
    op.create_table('NewsChangelog',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('NCLid', sa.String(length=64), nullable=False),
    sa.Column('NEid', sa.String(length=64), nullable=False),
    sa.Column('ADid', sa.String(length=64), nullable=False),
    sa.Column('NCLoperation', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('NCLid')
    )
    op.create_table('NewsComment',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('NCid', sa.String(length=64), nullable=False),
    sa.Column('NEid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('USname', sa.String(length=255), nullable=True),
    sa.Column('USheader', sa.Text(), nullable=True),
    sa.Column('NCtext', sa.String(length=140), nullable=True),
    sa.Column('NCparentid', sa.String(length=64), nullable=True),
    sa.Column('NCrootid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('NCid')
    )
    op.create_table('NewsCommentFavorite',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('NCFid', sa.String(length=64), nullable=False),
    sa.Column('NCid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('NCFid')
    )
    op.create_table('NewsFavorite',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('NEFid', sa.String(length=64), nullable=False),
    sa.Column('NEid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('NEFid')
    )
    op.create_table('NewsImage',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('NIid', sa.String(length=64), nullable=False),
    sa.Column('NEid', sa.String(length=64), nullable=False),
    sa.Column('NIimage', sa.String(length=255), nullable=False),
    sa.Column('NIsort', sa.Integer(), nullable=True),
    sa.Column('NIthumbnail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('NIid')
    )
    op.create_table('NewsTag',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('NTid', sa.String(length=64), nullable=False),
    sa.Column('NEid', sa.String(length=64), nullable=False),
    sa.Column('ITid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('NTid')
    )
    op.create_table('NewsTrample',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('NETid', sa.String(length=64), nullable=False),
    sa.Column('NEid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('NETid')
    )
    op.create_table('NewsVideo',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('NVid', sa.String(length=64), nullable=False),
    sa.Column('NEid', sa.String(length=64), nullable=False),
    sa.Column('NVvideo', sa.String(length=255), nullable=False),
    sa.Column('NVthumbnail', sa.String(length=255), nullable=False),
    sa.Column('NVduration', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('NVid')
    )
    op.create_table('OrderEvaluation',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OEid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('USname', sa.String(length=255), nullable=True),
    sa.Column('USheader', sa.Text(), nullable=True),
    sa.Column('OPid', sa.String(length=64), nullable=False),
    sa.Column('OMid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('SKUattriteDetail', sa.Text(), nullable=False),
    sa.Column('OEtext', sa.String(length=255), nullable=False),
    sa.Column('OEscore', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('OEid')
    )
    op.create_table('OrderEvaluationImage',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OEIid', sa.String(length=64), nullable=False),
    sa.Column('OEid', sa.String(length=64), nullable=False),
    sa.Column('OEImg', sa.String(length=255), nullable=False),
    sa.Column('OEIsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('OEIid')
    )
    op.create_table('OrderEvaluationVideo',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OEVid', sa.String(length=64), nullable=False),
    sa.Column('OEid', sa.String(length=64), nullable=False),
    sa.Column('OEVideo', sa.String(length=255), nullable=False),
    sa.Column('OEVthumbnail', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('OEVid')
    )
    op.create_table('OrderLogistics',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OLid', sa.String(length=64), nullable=False),
    sa.Column('OMid', sa.String(length=64), nullable=False),
    sa.Column('OLcompany', sa.String(length=32), nullable=False),
    sa.Column('OLexpressNo', sa.String(length=64), nullable=False),
    sa.Column('OLsearchStatus', sa.String(length=8), nullable=True),
    sa.Column('OLsignStatus', sa.Integer(), nullable=True),
    sa.Column('OLdata', sa.Text(), nullable=True),
    sa.Column('OLlastresult', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('OLid')
    )
    op.create_table('OrderMain',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OMid', sa.String(length=64), nullable=False),
    sa.Column('OMno', sa.String(length=64), nullable=False),
    sa.Column('OPayno', sa.String(length=64), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('UseCoupon', sa.Boolean(), nullable=True),
    sa.Column('OMfrom', sa.Integer(), nullable=True),
    sa.Column('PBname', sa.String(length=32), nullable=False),
    sa.Column('PBid', sa.String(length=64), nullable=False),
    sa.Column('OMclient', sa.Integer(), nullable=True),
    sa.Column('OMfreight', sa.Float(), nullable=True),
    sa.Column('OMmount', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('OMtrueMount', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('OMstatus', sa.Integer(), nullable=True),
    sa.Column('OMinRefund', sa.Boolean(), nullable=True),
    sa.Column('OMmessage', sa.String(length=255), nullable=True),
    sa.Column('OMrecvPhone', sa.String(length=11), nullable=False),
    sa.Column('OMrecvName', sa.String(length=11), nullable=False),
    sa.Column('OMrecvAddress', sa.String(length=255), nullable=False),
    sa.Column('PRcreateId', sa.String(length=64), nullable=True),
    sa.Column('OMlogisticType', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('OMid')
    )
    op.create_table('OrderMainContent',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OCAid', sa.String(length=64), nullable=False),
    sa.Column('CAfrom', sa.Integer(), nullable=True),
    sa.Column('OPid', sa.String(length=64), nullable=True),
    sa.Column('OCAcontentid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('OCAid')
    )
    op.create_table('OrderPart',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OPid', sa.String(length=64), nullable=False),
    sa.Column('OMid', sa.String(length=64), nullable=False),
    sa.Column('SKUid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('PRattribute', sa.Text(), nullable=True),
    sa.Column('SKUattriteDetail', sa.Text(), nullable=False),
    sa.Column('SKUprice', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('PRtitle', sa.String(length=255), nullable=False),
    sa.Column('SKUsn', sa.String(length=64), nullable=True),
    sa.Column('PCname', sa.String(length=255), nullable=True),
    sa.Column('PRmainpic', sa.String(length=255), nullable=False),
    sa.Column('OPnum', sa.Integer(), nullable=True),
    sa.Column('OPsubTotal', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('OPsubTrueTotal', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('OPisinORA', sa.Boolean(), nullable=True),
    sa.Column('PRfrom', sa.Integer(), nullable=True),
    sa.Column('SkudevideRate', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('UPperid', sa.String(length=64), nullable=True),
    sa.Column('UPperid2', sa.String(length=64), nullable=True),
    sa.Column('UPperid3', sa.String(length=64), nullable=True),
    sa.Column('USCommission1', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('USCommission2', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('USCommission3', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('UseCoupon', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('OPid')
    )
    op.create_table('OrderPay',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OPayid', sa.String(length=64), nullable=False),
    sa.Column('OPayno', sa.String(length=64), nullable=True),
    sa.Column('OPayType', sa.Integer(), nullable=True),
    sa.Column('OPaytime', sa.DateTime(), nullable=True),
    sa.Column('OPayMount', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('OPaysn', sa.String(length=64), nullable=True),
    sa.Column('OPayJson', sa.Text(), nullable=True),
    sa.Column('OPaymarks', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('OPayid')
    )
    op.create_index(op.f('ix_OrderPay_OPayno'), 'OrderPay', ['OPayno'], unique=False)
    op.create_table('OrderRaward',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OCid', sa.String(length=64), nullable=False),
    sa.Column('COid', sa.String(length=64), nullable=False),
    sa.Column('OMid', sa.String(length=64), nullable=False),
    sa.Column('OCreduce', sa.Float(), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('OCid')
    )
    op.create_table('OrderRefund',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ORid', sa.String(length=64), nullable=False),
    sa.Column('OMid', sa.String(length=64), nullable=False),
    sa.Column('OPid', sa.String(length=64), nullable=True),
    sa.Column('ORAid', sa.String(length=64), nullable=False),
    sa.Column('ORrecvname', sa.String(length=16), nullable=False),
    sa.Column('ORrecvphone', sa.String(length=11), nullable=False),
    sa.Column('ORrecvaddress', sa.String(length=255), nullable=False),
    sa.Column('ORstatus', sa.Integer(), nullable=True),
    sa.Column('ORlogisticCompany', sa.String(length=32), nullable=True),
    sa.Column('ORlogisticsn', sa.String(length=64), nullable=True),
    sa.Column('ORlogisticSignStatus', sa.Integer(), nullable=True),
    sa.Column('ORlogisticData', sa.Text(), nullable=True),
    sa.Column('ORlogisticLostResult', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ORid')
    )
    op.create_index(op.f('ix_OrderRefund_ORAid'), 'OrderRefund', ['ORAid'], unique=False)
    op.create_table('OrderRefundApply',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ORAid', sa.String(length=64), nullable=False),
    sa.Column('ORAsn', sa.String(length=64), nullable=False),
    sa.Column('OMid', sa.String(length=64), nullable=True),
    sa.Column('OPid', sa.String(length=64), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('ORAstate', sa.Integer(), nullable=True),
    sa.Column('ORAreason', sa.String(length=255), nullable=False),
    sa.Column('ORAmount', sa.Float(), nullable=False),
    sa.Column('ORAaddtion', sa.String(length=255), nullable=True),
    sa.Column('ORaddtionVoucher', sa.Text(), nullable=True),
    sa.Column('ORAproductStatus', sa.Integer(), nullable=True),
    sa.Column('ORAstatus', sa.Integer(), nullable=True),
    sa.Column('ORAcheckReason', sa.String(length=255), nullable=True),
    sa.Column('ORAcheckUser', sa.String(length=64), nullable=True),
    sa.Column('ORAcheckTime', sa.DateTime(), nullable=True),
    sa.Column('ORAnote', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ORAid')
    )
    op.create_table('OrderRefundFlow',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ORFid', sa.String(length=64), nullable=False),
    sa.Column('ORAid', sa.String(length=64), nullable=False),
    sa.Column('ORAmount', sa.Float(), nullable=False),
    sa.Column('OPayno', sa.String(length=64), nullable=False),
    sa.Column('OPayType', sa.String(length=64), nullable=True),
    sa.Column('ORFoutRequestNo', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ORFid')
    )
    op.create_table('OrderRefundNotes',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ORNid', sa.String(length=64), nullable=False),
    sa.Column('OMid', sa.String(length=64), nullable=True),
    sa.Column('OPid', sa.String(length=64), nullable=True),
    sa.Column('UserName', sa.String(length=32), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('ORNaction', sa.Integer(), nullable=True),
    sa.Column('ORNabo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ORNid')
    )
    op.create_index(op.f('ix_OrderRefundNotes_OMid'), 'OrderRefundNotes', ['OMid'], unique=False)
    op.create_index(op.f('ix_OrderRefundNotes_OPid'), 'OrderRefundNotes', ['OPid'], unique=False)
    op.create_table('OutStock',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OSid', sa.String(length=64), nullable=False),
    sa.Column('SKUid', sa.String(length=64), nullable=False),
    sa.Column('OSnum', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('OSid')
    )
    op.create_table('Permission',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PEid', sa.String(length=64), nullable=False),
    sa.Column('PELevel', sa.Integer(), nullable=False),
    sa.Column('PIid', sa.String(length=64), nullable=True),
    sa.Column('PTid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('PEid')
    )
    op.create_table('PermissionItems',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PIid', sa.String(length=64), nullable=False),
    sa.Column('PIname', sa.Text(), nullable=True),
    sa.Column('PIstatus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('PIid')
    )
    op.create_table('PermissionNotes',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PNid', sa.String(length=64), nullable=False),
    sa.Column('ADid', sa.String(length=64), nullable=True),
    sa.Column('PNcontent', sa.String(length=64), nullable=True),
    sa.Column('PINaction', sa.Text(), nullable=True),
    sa.Column('PNType', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('PNid')
    )
    op.create_table('PermissionType',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PTid', sa.String(length=64), nullable=False),
    sa.Column('PTname', sa.Text(), nullable=True),
    sa.Column('PTmodelName', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('PTid')
    )
    op.create_table('ProductBrand',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PBid', sa.String(length=64), nullable=False),
    sa.Column('PBlogo', sa.String(length=255), nullable=True),
    sa.Column('PBname', sa.Text(), nullable=True),
    sa.Column('PBdesc', sa.Text(), nullable=True),
    sa.Column('PBlinks', sa.String(length=255), nullable=True),
    sa.Column('PBbackgroud', sa.String(length=255), nullable=True),
    sa.Column('PBstatus', sa.Integer(), nullable=True),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('PBid')
    )
    op.create_table('ProductCategory',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PCid', sa.String(length=64), nullable=False),
    sa.Column('PCtype', sa.Integer(), nullable=False),
    sa.Column('PCname', sa.String(length=16), nullable=False),
    sa.Column('PCdesc', sa.String(length=125), nullable=True),
    sa.Column('ParentPCid', sa.String(length=64), nullable=True),
    sa.Column('PCsort', sa.Integer(), nullable=True),
    sa.Column('PCpic', sa.String(length=255), nullable=True),
    sa.Column('PCtopPic', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('PCid')
    )
    op.create_table('ProductImage',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PIid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('PIpic', sa.String(length=255), nullable=False),
    sa.Column('PIsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('PIid')
    )
    op.create_table('ProductItems',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PIid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('ITid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('PIid')
    )
    op.create_table('ProductMonthSaleValue',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PMSVid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('PMSVnum', sa.BIGINT(), nullable=True),
    sa.Column('PMSVfakenum', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('PMSVid')
    )
    op.create_table('ProductScene',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PSid', sa.String(length=64), nullable=False),
    sa.Column('PSpic', sa.String(length=255), nullable=False),
    sa.Column('PSname', sa.String(length=16), nullable=False),
    sa.Column('PSsort', sa.Integer(), nullable=True),
    sa.Column('PStimelimited', sa.Boolean(), nullable=True),
    sa.Column('PSstarttime', sa.DateTime(), nullable=True),
    sa.Column('PSendtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('PSid')
    )
    op.create_table('ProductSku',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SKUid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('SKUpic', sa.String(length=255), nullable=False),
    sa.Column('SKUattriteDetail', sa.Text(), nullable=True),
    sa.Column('SKUprice', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SKUstock', sa.BIGINT(), nullable=True),
    sa.Column('SKUsn', sa.String(length=64), nullable=False),
    sa.Column('SkudevideRate', sa.DECIMAL(scale=2), nullable=True),
    sa.PrimaryKeyConstraint('SKUid')
    )
    op.create_table('ProductSkuValue',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PSKUid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('PSKUvalue', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('PSKUid')
    )
    op.create_table('ProductUrl',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PUid', sa.String(length=64), nullable=False),
    sa.Column('PUurl', sa.Text(), nullable=False),
    sa.Column('PUdir', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('PUid')
    )
    op.create_table('Products',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('PRtitle', sa.String(length=255), nullable=False),
    sa.Column('PRprice', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('PRlinePrice', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('PRfreight', sa.Float(precision=10), nullable=True),
    sa.Column('PRstocks', sa.BIGINT(), nullable=True),
    sa.Column('PRsalesValue', sa.Integer(), nullable=True),
    sa.Column('PRstatus', sa.Integer(), nullable=True),
    sa.Column('PRmainpic', sa.String(length=255), nullable=True),
    sa.Column('PRattribute', sa.Text(), nullable=True),
    sa.Column('PCid', sa.String(length=64), nullable=True),
    sa.Column('PBid', sa.String(length=64), nullable=True),
    sa.Column('PRdesc', mysql.LONGTEXT(), nullable=True),
    sa.Column('PRremarks', sa.String(length=255), nullable=True),
    sa.Column('PRfrom', sa.Integer(), nullable=True),
    sa.Column('PRdescription', sa.Text(), nullable=True),
    sa.Column('CreaterId', sa.String(length=64), nullable=False),
    sa.Column('PRfeatured', sa.Boolean(), nullable=True),
    sa.Column('PRaverageScore', sa.Float(precision=10), nullable=True),
    sa.Column('PRcode', sa.String(length=64), nullable=True),
    sa.Column('PRpromotion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('PRid')
    )
    op.create_table('Quest',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('QUid', sa.String(length=64), nullable=False),
    sa.Column('QOid', sa.String(length=64), nullable=True),
    sa.Column('QUquest', sa.Text(), nullable=True),
    sa.Column('QUstatus', sa.Integer(), nullable=True),
    sa.Column('QUcreateId', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('QUid')
    )
    op.create_table('QuestAnswerNote',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('QANid', sa.String(length=64), nullable=False),
    sa.Column('QANcontent', sa.Text(), nullable=True),
    sa.Column('QANcreateid', sa.String(length=64), nullable=True),
    sa.Column('QANtargetId', sa.String(length=64), nullable=True),
    sa.Column('QANtype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('QANid')
    )
    op.create_table('QuestOutline',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('QOid', sa.String(length=64), nullable=False),
    sa.Column('QOicon', sa.Text(), nullable=True),
    sa.Column('QOname', sa.Text(), nullable=True),
    sa.Column('QOstatus', sa.Integer(), nullable=True),
    sa.Column('QOcreateId', sa.String(length=64), nullable=True),
    sa.Column('QOtype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('QOid')
    )
    op.create_table('SceneItem',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SIid', sa.String(length=64), nullable=False),
    sa.Column('PSid', sa.String(length=64), nullable=False),
    sa.Column('ITid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('SIid')
    )
    op.create_table('SettlenmentApply',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SSAid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.Column('SSid', sa.String(length=64), nullable=True),
    sa.Column('SSAabo', sa.Text(), nullable=True),
    sa.Column('SSArejectReason', sa.Text(), nullable=True),
    sa.Column('SSAstatus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('SSAid')
    )
    op.create_table('SignInAward',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SIAid', sa.String(length=64), nullable=False),
    sa.Column('SIAday', sa.Integer(), nullable=True),
    sa.Column('SIAnum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('SIAid')
    )
    op.create_table('Supplizer',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SUid', sa.String(length=64), nullable=False),
    sa.Column('SUloginPhone', sa.String(length=11), nullable=False),
    sa.Column('SUlinkPhone', sa.String(length=11), nullable=True),
    sa.Column('SUname', sa.String(length=32), nullable=True),
    sa.Column('SUlinkman', sa.String(length=16), nullable=False),
    sa.Column('SUaddress', sa.String(length=255), nullable=False),
    sa.Column('SUstatus', sa.Integer(), nullable=True),
    sa.Column('SUisseller', sa.Boolean(), nullable=True),
    sa.Column('SUbaseRate', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('SUdeposit', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('SUbanksn', sa.String(length=32), nullable=True),
    sa.Column('SUbankname', sa.String(length=64), nullable=True),
    sa.Column('SUpassword', sa.String(length=255), nullable=True),
    sa.Column('SUheader', sa.String(length=255), nullable=True),
    sa.Column('SUcontract', sa.Text(), nullable=True),
    sa.Column('SUbusinessLicense', sa.Text(), nullable=True),
    sa.Column('SUregisteredFund', sa.String(length=255), nullable=True),
    sa.Column('SUmainCategory', sa.Text(), nullable=True),
    sa.Column('SUregisteredTime', sa.DateTime(), nullable=True),
    sa.Column('SUlegalPerson', sa.Text(), nullable=True),
    sa.Column('SUemail', sa.String(length=256), nullable=True),
    sa.Column('SUlegalPersonIDcardFront', sa.Text(), nullable=True),
    sa.Column('SUlegalPersonIDcardBack', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('SUid')
    )
    op.create_index(op.f('ix_Supplizer_SUloginPhone'), 'Supplizer', ['SUloginPhone'], unique=True)
    op.create_table('SupplizerAccount',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SAid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.Column('SAbankName', sa.Text(), nullable=True),
    sa.Column('SAbankDetail', sa.Text(), nullable=True),
    sa.Column('SAcardNo', sa.String(length=32), nullable=True),
    sa.Column('SAcardName', sa.Text(), nullable=True),
    sa.Column('SACompanyName', sa.Text(), nullable=True),
    sa.Column('SAICIDcode', sa.Text(), nullable=True),
    sa.Column('SAaddress', sa.Text(), nullable=True),
    sa.Column('SAbankAccount', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('SAid')
    )
    op.create_table('SupplizerDepositLog',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SDLid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.Column('SDLnum', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SDafter', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SDbefore', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SDLacid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('SDLid')
    )
    op.create_table('SupplizerProduct',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SPid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('SPid')
    )
    op.create_index(op.f('ix_SupplizerProduct_PRid'), 'SupplizerProduct', ['PRid'], unique=False)
    op.create_table('SupplizerSettlement',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SSid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.Column('SSstatus', sa.Integer(), nullable=True),
    sa.Column('SSdealTime', sa.DateTime(), nullable=True),
    sa.Column('SSdealamount', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('SSid')
    )
    op.create_table('TimeLimitedApply',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('TLAid', sa.String(length=64), nullable=False),
    sa.Column('TLAstartTime', sa.DateTime(), nullable=True),
    sa.Column('TLAendTime', sa.DateTime(), nullable=True),
    sa.Column('TLAstatus', sa.Integer(), nullable=True),
    sa.Column('ADid', sa.String(length=64), nullable=True),
    sa.Column('TLAsort', sa.Integer(), nullable=True),
    sa.Column('TLAtopPic', sa.Text(), nullable=True),
    sa.Column('TlAname', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('TLAid')
    )
    op.create_table('TimeLimitedProduct',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('TLPid', sa.String(length=64), nullable=False),
    sa.Column('TLAid', sa.String(length=64), nullable=True),
    sa.Column('TLAfrom', sa.Integer(), nullable=True),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=True),
    sa.Column('TLArejectReson', sa.String(length=255), nullable=True),
    sa.Column('TLAstatus', sa.Integer(), nullable=True),
    sa.Column('PRprice', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('TLPid')
    )
    op.create_table('TimeLimitedSku',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('TLSid', sa.String(length=64), nullable=False),
    sa.Column('TLPid', sa.String(length=64), nullable=True),
    sa.Column('TLSstock', sa.String(length=64), nullable=True),
    sa.Column('SKUid', sa.String(length=64), nullable=True),
    sa.Column('SKUprice', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('TLSid')
    )
    op.create_table('TrialCommodity',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('TCid', sa.String(length=64), nullable=False),
    sa.Column('TCtitle', sa.String(length=255), nullable=False),
    sa.Column('TCdescription', sa.Text(), nullable=True),
    sa.Column('TCdeposit', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('TCdeadline', sa.Integer(), nullable=False),
    sa.Column('TCfreight', sa.Float(), nullable=True),
    sa.Column('TCfrom', sa.Integer(), nullable=True),
    sa.Column('TCstocks', sa.BIGINT(), nullable=True),
    sa.Column('TCsalesValue', sa.BIGINT(), nullable=True),
    sa.Column('TCstatus', sa.Integer(), nullable=True),
    sa.Column('TCmainpic', sa.String(length=255), nullable=True),
    sa.Column('TCattribute', sa.Text(), nullable=True),
    sa.Column('TCdesc', mysql.LONGTEXT(), nullable=True),
    sa.Column('TCremarks', sa.String(length=255), nullable=True),
    sa.Column('CreaterId', sa.String(length=64), nullable=False),
    sa.Column('PBid', sa.String(length=64), nullable=True),
    sa.Column('ApplyStartTime', sa.Date(), nullable=False),
    sa.Column('ApplyEndTime', sa.Date(), nullable=False),
    sa.Column('AgreeStartTime', sa.Date(), nullable=True),
    sa.Column('AgreeEndTime', sa.Date(), nullable=True),
    sa.Column('TCrejectReason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('TCid')
    )
    op.create_table('TrialCommodityImage',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('TCIid', sa.String(length=64), nullable=False),
    sa.Column('TCid', sa.String(length=64), nullable=False),
    sa.Column('TCIpic', sa.String(length=255), nullable=False),
    sa.Column('TCIsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('TCIid')
    )
    op.create_table('TrialCommoditySku',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SKUid', sa.String(length=64), nullable=False),
    sa.Column('TCid', sa.String(length=64), nullable=False),
    sa.Column('SKUpic', sa.String(length=255), nullable=False),
    sa.Column('SKUattriteDetail', sa.Text(), nullable=True),
    sa.Column('SKUprice', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('SKUstock', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('SKUid')
    )
    op.create_table('TrialCommoditySkuValue',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('TSKUid', sa.String(length=64), nullable=False),
    sa.Column('TCid', sa.String(length=64), nullable=False),
    sa.Column('TSKUvalue', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('TSKUid')
    )
    op.create_table('User',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('USname', sa.String(length=255), nullable=False),
    sa.Column('USrealname', sa.String(length=255), nullable=True),
    sa.Column('UStelphone', sa.String(length=13), nullable=True),
    sa.Column('USgender', sa.Integer(), nullable=True),
    sa.Column('USbirthday', sa.DateTime(), nullable=True),
    sa.Column('USidentification', sa.String(length=24), nullable=True),
    sa.Column('USheader', sa.Text(), nullable=True),
    sa.Column('USopenid1', sa.Text(), nullable=True),
    sa.Column('USopenid2', sa.Text(), nullable=True),
    sa.Column('USsupper1', sa.String(length=64), nullable=True),
    sa.Column('USsupper2', sa.String(length=64), nullable=True),
    sa.Column('USsupper3', sa.String(length=64), nullable=True),
    sa.Column('USCommission1', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('USCommission2', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('USCommission3', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('USintegral', sa.Integer(), nullable=True),
    sa.Column('CommisionLevel', sa.Integer(), nullable=True),
    sa.Column('USlevel', sa.Integer(), nullable=True),
    sa.Column('USfrom', sa.Integer(), nullable=True),
    sa.Column('USqrcode', sa.Text(), nullable=True),
    sa.Column('USpaycode', sa.Text(), nullable=True),
    sa.Column('UScontinuous', sa.Integer(), nullable=True),
    sa.Column('UStoAgentTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('USid')
    )
    op.create_table('UserActivationCode',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UACid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('UACcode', sa.String(length=16), nullable=False),
    sa.Column('UACstatus', sa.Integer(), nullable=True),
    sa.Column('UACuseFor', sa.String(length=64), nullable=True),
    sa.Column('UACtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('UACid')
    )
    op.create_index(op.f('ix_UserActivationCode_UACcode'), 'UserActivationCode', ['UACcode'], unique=False)
    op.create_index(op.f('ix_UserActivationCode_USid'), 'UserActivationCode', ['USid'], unique=False)
    op.create_table('UserAddress',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UAid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('UAname', sa.String(length=16), nullable=False),
    sa.Column('UAphone', sa.String(length=16), nullable=False),
    sa.Column('UAtext', sa.String(length=255), nullable=False),
    sa.Column('UApostalcode', sa.String(length=8), nullable=True),
    sa.Column('UAdefault', sa.Boolean(), nullable=True),
    sa.Column('AAid', sa.String(length=8), nullable=False),
    sa.Column('UAFrom', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('UAid')
    )
    op.create_table('UserCommission',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UCid', sa.String(length=64), nullable=False),
    sa.Column('UCcommission', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('CommisionFor', sa.Integer(), nullable=True),
    sa.Column('FromUsid', sa.String(length=64), nullable=True),
    sa.Column('UCstatus', sa.Integer(), nullable=True),
    sa.Column('UCtype', sa.Integer(), nullable=True),
    sa.Column('UCendTime', sa.DateTime(), nullable=True),
    sa.Column('PRtitle', sa.String(length=255), nullable=True),
    sa.Column('SKUpic', sa.Text(), nullable=True),
    sa.Column('OMid', sa.String(length=64), nullable=True),
    sa.Column('OPid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('UCid')
    )
    op.create_table('UserInvitation',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UINid', sa.String(length=64), nullable=False),
    sa.Column('USInviter', sa.String(length=64), nullable=True),
    sa.Column('USInvited', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('UINid')
    )
    op.create_table('UserLoginTime',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ULTid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('USTip', sa.String(length=64), nullable=True),
    sa.Column('ULtype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ULTid')
    )
    op.create_table('UserMetia',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UMid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('UMurl', sa.Text(), nullable=True),
    sa.Column('UMtype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('UMid')
    )
    op.create_table('UserSalesvolume',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('USVid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('USVamount', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('USVamountagent', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('USVid')
    )
    op.create_table('UserSearchHistory',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('USHid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('USHname', sa.String(length=64), nullable=False),
    sa.Column('USHtype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('USHid')
    )
    op.create_table('UserSignIn',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UIid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('UIintegral', sa.Integer(), nullable=True),
    sa.Column('UIaction', sa.Integer(), nullable=True),
    sa.Column('UItype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('UIid')
    )
    op.create_table('UserWallet',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UWid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('CommisionFor', sa.Integer(), nullable=True),
    sa.Column('UWbalance', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('UWtotal', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('UWcash', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('UWexpect', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('UWid')
    )
    op.create_table('UserWords',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UWid', sa.String(length=64), nullable=False),
    sa.Column('UWmessage', sa.Text(), nullable=False),
    sa.Column('UWname', sa.String(length=64), nullable=True),
    sa.Column('UWtelphone', sa.String(length=14), nullable=True),
    sa.Column('UWemail', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('UWid')
    )
    op.create_table('identifyingcode',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ICid', sa.String(length=64), nullable=False),
    sa.Column('ICtelphone', sa.String(length=14), nullable=False),
    sa.Column('ICcode', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('ICid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identifyingcode')
    op.drop_table('UserWords')
    op.drop_table('UserWallet')
    op.drop_table('UserSignIn')
    op.drop_table('UserSearchHistory')
    op.drop_table('UserSalesvolume')
    op.drop_table('UserMetia')
    op.drop_table('UserLoginTime')
    op.drop_table('UserInvitation')
    op.drop_table('UserCommission')
    op.drop_table('UserAddress')
    op.drop_index(op.f('ix_UserActivationCode_USid'), table_name='UserActivationCode')
    op.drop_index(op.f('ix_UserActivationCode_UACcode'), table_name='UserActivationCode')
    op.drop_table('UserActivationCode')
    op.drop_table('User')
    op.drop_table('TrialCommoditySkuValue')
    op.drop_table('TrialCommoditySku')
    op.drop_table('TrialCommodityImage')
    op.drop_table('TrialCommodity')
    op.drop_table('TimeLimitedSku')
    op.drop_table('TimeLimitedProduct')
    op.drop_table('TimeLimitedApply')
    op.drop_table('SupplizerSettlement')
    op.drop_index(op.f('ix_SupplizerProduct_PRid'), table_name='SupplizerProduct')
    op.drop_table('SupplizerProduct')
    op.drop_table('SupplizerDepositLog')
    op.drop_table('SupplizerAccount')
    op.drop_index(op.f('ix_Supplizer_SUloginPhone'), table_name='Supplizer')
    op.drop_table('Supplizer')
    op.drop_table('SignInAward')
    op.drop_table('SettlenmentApply')
    op.drop_table('SceneItem')
    op.drop_table('QuestOutline')
    op.drop_table('QuestAnswerNote')
    op.drop_table('Quest')
    op.drop_table('Products')
    op.drop_table('ProductUrl')
    op.drop_table('ProductSkuValue')
    op.drop_table('ProductSku')
    op.drop_table('ProductScene')
    op.drop_table('ProductMonthSaleValue')
    op.drop_table('ProductItems')
    op.drop_table('ProductImage')
    op.drop_table('ProductCategory')
    op.drop_table('ProductBrand')
    op.drop_table('PermissionType')
    op.drop_table('PermissionNotes')
    op.drop_table('PermissionItems')
    op.drop_table('Permission')
    op.drop_table('OutStock')
    op.drop_index(op.f('ix_OrderRefundNotes_OPid'), table_name='OrderRefundNotes')
    op.drop_index(op.f('ix_OrderRefundNotes_OMid'), table_name='OrderRefundNotes')
    op.drop_table('OrderRefundNotes')
    op.drop_table('OrderRefundFlow')
    op.drop_table('OrderRefundApply')
    op.drop_index(op.f('ix_OrderRefund_ORAid'), table_name='OrderRefund')
    op.drop_table('OrderRefund')
    op.drop_table('OrderRaward')
    op.drop_index(op.f('ix_OrderPay_OPayno'), table_name='OrderPay')
    op.drop_table('OrderPay')
    op.drop_table('OrderPart')
    op.drop_table('OrderMainContent')
    op.drop_table('OrderMain')
    op.drop_table('OrderLogistics')
    op.drop_table('OrderEvaluationVideo')
    op.drop_table('OrderEvaluationImage')
    op.drop_table('OrderEvaluation')
    op.drop_table('NewsVideo')
    op.drop_table('NewsTrample')
    op.drop_table('NewsTag')
    op.drop_table('NewsImage')
    op.drop_table('NewsFavorite')
    op.drop_table('NewsCommentFavorite')
    op.drop_table('NewsComment')
    op.drop_table('NewsChangelog')
    op.drop_table('News')
    op.drop_table('ManagerSystemNotes')
    op.drop_table('MagixBoxOpen')
    op.drop_table('MagicBoxJoin')
    op.drop_table('MagicBoxFlow')
    op.drop_table('MagicBoxApply')
    op.drop_index(op.f('ix_LogisticsCompnay_LCfirstCharater'), table_name='LogisticsCompnay')
    op.drop_index(op.f('ix_LogisticsCompnay_LCcode'), table_name='LogisticsCompnay')
    op.drop_table('LogisticsCompnay')
    op.drop_index(op.f('ix_Items_ITtype'), table_name='Items')
    op.drop_table('Items')
    op.drop_table('IndexBanner')
    op.drop_table('IDcheck')
    op.drop_table('GuessNumAwardSku')
    op.drop_table('GuessNumAwardProduct')
    op.drop_table('GuessNumAward')
    op.drop_table('GuessNum')
    op.drop_table('GuessAwardFlow')
    op.drop_table('FreshManJoinFlow')
    op.drop_table('FreshManFirstSku')
    op.drop_table('FreshManFirstProduct')
    op.drop_table('FreshManFirstApply')
    op.drop_table('DisputeType')
    op.drop_table('CouponUser')
    op.drop_table('CouponItem')
    op.drop_table('CouponFor')
    op.drop_table('Coupon')
    op.drop_table('CounponHistory')
    op.drop_table('CorrectNum')
    op.drop_table('CompanyMessage')
    op.drop_table('Commision')
    op.drop_table('CashNotes')
    op.drop_table('Carts')
    op.drop_table('BrandwithItems')
    op.drop_table('ApprovalNotes')
    op.drop_table('Approval')
    op.drop_table('AnswerUser')
    op.drop_table('Answer')
    op.drop_table('AdminPermission')
    op.drop_table('AdminNotes')
    op.drop_table('Admin')
    op.drop_table('AddressProvince')
    op.drop_table('AddressCity')
    op.drop_table('AddressArea')
    op.drop_index(op.f('ix_Activity_ACtype'), table_name='Activity')
    op.drop_table('Activity')
    op.drop_table('ActivationCodeRule')
    op.drop_table('ActivationCodeApply')
    # ### end Alembic commands ###
