"""订单类型字段

Revision ID: f52fe47267e8
Revises: 553a3b282001
Create Date: 2018-12-13 18:42:47.656301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52fe47267e8'
down_revision = '553a3b282001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderMain', sa.Column('OMlogisticType', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderMain', 'OMlogisticType')
    # ### end Alembic commands ###
