"""brands

Revision ID: f8dbfb0ad4b3
Revises: 8596c32a2195
Create Date: 2018-11-08 09:41:17.337934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8dbfb0ad4b3'
down_revision = '8596c32a2195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProductBrand', sa.Column('PBdesc', sa.String(length=255), nullable=True))
    op.add_column('ProductBrand', sa.Column('PBlinks', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ProductBrand', 'PBlinks')
    op.drop_column('ProductBrand', 'PBdesc')
    # ### end Alembic commands ###
