"""供应商

Revision ID: fa3e893cb5dd
Revises: 6061a7f254bc
Create Date: 2018-12-03 13:19:50.223995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa3e893cb5dd'
down_revision = '6061a7f254bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magic_box_join',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('MBJid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('MABid', sa.String(length=64), nullable=False),
    sa.Column('MBJprice', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('MBJid')
    )
    op.create_table('magix_box_open',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('MBOid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('MBJid', sa.String(length=64), nullable=False),
    sa.Column('MBOgear', sa.Integer(), nullable=False),
    sa.Column('MBOresult', sa.Float(), nullable=False),
    sa.Column('MBOprice', sa.Float(), nullable=False),
    sa.Column('MBOhasShare', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('MBOid')
    )
    op.create_table('supplizer',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SUid', sa.String(length=64), nullable=False),
    sa.Column('SUname', sa.String(length=16), nullable=False),
    sa.Column('SUlinkman', sa.String(length=16), nullable=False),
    sa.Column('SUlinkPhone', sa.String(length=11), nullable=False),
    sa.Column('SUaddress', sa.String(length=255), nullable=False),
    sa.Column('SUstatus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('SUid')
    )
    op.add_column('Supplizer', sa.Column('SUbankname', sa.String(length=64), nullable=True))
    op.add_column('Supplizer', sa.Column('SUbanksn', sa.String(length=32), nullable=True))
    op.drop_column('Supplizer', 'SUbank')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Supplizer', sa.Column('SUbank', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('Supplizer', 'SUbanksn')
    op.drop_column('Supplizer', 'SUbankname')
    op.drop_table('supplizer')
    op.drop_table('magix_box_open')
    op.drop_table('magic_box_join')
    # ### end Alembic commands ###
