"""add_cashflow

Revision ID: fa474cdc0c54
Revises: 07873d2d8c2b
Create Date: 2019-05-05 17:07:50.364975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa474cdc0c54'
down_revision = '07873d2d8c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CashFlow',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('CFWid', sa.String(length=64), nullable=False),
    sa.Column('CNid', sa.String(length=64), nullable=False),
    sa.Column('partner_trade_no', sa.String(length=64), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('amout', sa.Integer(), nullable=True),
    sa.Column('cmms_amt', sa.Integer(), nullable=True),
    sa.Column('CFWfrom', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('CFWid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CashFlow')
    # ### end Alembic commands ###
