"""'add'

Revision ID: fcb2369df4d5
Revises: fa4cfe3c88f5
Create Date: 2018-11-24 05:46:12.087028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb2369df4d5'
down_revision = 'fa4cfe3c88f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Admin', sa.Column('ADfirstname', sa.Text(), nullable=True))
    op.add_column('Admin', sa.Column('ADfirstpwd', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Admin', 'ADfirstpwd')
    op.drop_column('Admin', 'ADfirstname')
    # ### end Alembic commands ###
