"""add

Revision ID: fce77a241d2f
Revises: f46fc25a66b5
Create Date: 2019-04-22 11:46:16.076431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce77a241d2f'
down_revision = 'f46fc25a66b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserCollection',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UCLid', sa.String(length=64), nullable=False),
    sa.Column('UCLcollector', sa.String(length=64), nullable=True),
    sa.Column('UCLcollection', sa.String(length=64), nullable=True),
    sa.Column('UCLcoType', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('UCLid')
    )
    op.create_table('UserTransmit',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UTid', sa.String(length=64), nullable=False),
    sa.Column('Contentid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('UTtype', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('UTid')
    )
    op.add_column('Supplizer', sa.Column('SUgrade', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('USgrade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'USgrade')
    op.drop_column('Supplizer', 'SUgrade')
    op.drop_table('UserTransmit')
    op.drop_table('UserCollection')
    # ### end Alembic commands ###
