"""TrialCommodity

Revision ID: fd498cf63c6a
Revises: f93f800e3e0b
Create Date: 2018-11-26 18:11:36.538524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd498cf63c6a'
down_revision = 'f93f800e3e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TrialCommodityImage',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('TCIid', sa.String(length=64), nullable=False),
    sa.Column('TCid', sa.String(length=64), nullable=False),
    sa.Column('TCIpic', sa.String(length=255), nullable=False),
    sa.Column('TCIsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('TCIid')
    )
    op.create_table('TrialCommoditySku',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SKUid', sa.String(length=64), nullable=False),
    sa.Column('TCid', sa.String(length=64), nullable=False),
    sa.Column('SKUpic', sa.String(length=255), nullable=False),
    sa.Column('SKUattriteDetail', sa.Text(), nullable=True),
    sa.Column('SKUstock', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('SKUid')
    )
    op.create_table('TrialCommoditySkuValue',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('TSKUid', sa.String(length=64), nullable=False),
    sa.Column('PSKUvalue', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('TSKUid')
    )
    op.add_column('TrialCommodity', sa.Column('CreaterId', sa.String(length=64), nullable=False))
    op.add_column('TrialCommodity', sa.Column('PRfreight', sa.Float(), nullable=True))
    op.add_column('TrialCommodity', sa.Column('TCattribute', sa.Text(), nullable=True))
    op.add_column('TrialCommodity', sa.Column('TCdeadline', sa.Integer(), nullable=False))
    op.add_column('TrialCommodity', sa.Column('TCdeposit', sa.Float(), nullable=False))
    op.add_column('TrialCommodity', sa.Column('TCdesc', sa.Text(), nullable=True))
    op.add_column('TrialCommodity', sa.Column('TCdescription', sa.Text(), nullable=True))
    op.add_column('TrialCommodity', sa.Column('TCmainpic', sa.String(length=255), nullable=True))
    op.add_column('TrialCommodity', sa.Column('TCremarks', sa.String(length=255), nullable=True))
    op.add_column('TrialCommodity', sa.Column('TCsalesValue', sa.Integer(), nullable=True))
    op.add_column('TrialCommodity', sa.Column('TCstatus', sa.Integer(), nullable=True))
    op.add_column('TrialCommodity', sa.Column('TCstocks', sa.Integer(), nullable=True))
    op.add_column('TrialCommodity', sa.Column('TCtitle', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TrialCommodity', 'TCtitle')
    op.drop_column('TrialCommodity', 'TCstocks')
    op.drop_column('TrialCommodity', 'TCstatus')
    op.drop_column('TrialCommodity', 'TCsalesValue')
    op.drop_column('TrialCommodity', 'TCremarks')
    op.drop_column('TrialCommodity', 'TCmainpic')
    op.drop_column('TrialCommodity', 'TCdescription')
    op.drop_column('TrialCommodity', 'TCdesc')
    op.drop_column('TrialCommodity', 'TCdeposit')
    op.drop_column('TrialCommodity', 'TCdeadline')
    op.drop_column('TrialCommodity', 'TCattribute')
    op.drop_column('TrialCommodity', 'PRfreight')
    op.drop_column('TrialCommodity', 'CreaterId')
    op.drop_table('TrialCommoditySkuValue')
    op.drop_table('TrialCommoditySku')
    op.drop_table('TrialCommodityImage')
    # ### end Alembic commands ###
