"""'add'

Revision ID: ff06d923722c
Revises: 6d4b37cfa46b
Create Date: 2019-04-11 15:56:33.687124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff06d923722c'
down_revision = '6d4b37cfa46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Carts', sa.Column('CAfrom', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Carts', 'CAfrom')
    # ### end Alembic commands ###
