"""'add'

Revision ID: fffc57636d09
Revises: 9f27301bfebc
Create Date: 2018-11-07 11:15:03.536012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffc57636d09'
down_revision = '9f27301bfebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ADid', sa.String(length=64), nullable=False),
    sa.Column('ADname', sa.String(length=255), nullable=True),
    sa.Column('ADpassword', sa.Text(), nullable=False),
    sa.Column('ADheader', sa.Text(), nullable=True),
    sa.Column('ADlevel', sa.Integer(), nullable=True),
    sa.Column('ADstatus', sa.Integer(), nullable=True),
    sa.Column('ADcreateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ADid')
    )
    op.create_table('AdminNotes',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ANid', sa.String(length=64), nullable=False),
    sa.Column('ADid', sa.String(length=64), nullable=False),
    sa.Column('ANcreateTime', sa.DateTime(), nullable=True),
    sa.Column('ANdoneid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ANid')
    )
    op.create_table('User',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('USname', sa.String(length=255), nullable=False),
    sa.Column('USrealname', sa.String(length=255), nullable=True),
    sa.Column('UStelphone', sa.String(length=13), nullable=False),
    sa.Column('USgender', sa.Integer(), nullable=True),
    sa.Column('USbirthday', sa.DateTime(), nullable=True),
    sa.Column('USidentification', sa.String(length=24), nullable=True),
    sa.Column('USheader', sa.Text(), nullable=True),
    sa.Column('USopenid1', sa.Text(), nullable=True),
    sa.Column('USopenid2', sa.Text(), nullable=True),
    sa.Column('USsupper1', sa.String(length=64), nullable=True),
    sa.Column('USsupper2', sa.String(length=64), nullable=True),
    sa.Column('USCommission', sa.Float(), nullable=True),
    sa.Column('USintegral', sa.Integer(), nullable=True),
    sa.Column('USlevel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('USid')
    )
    op.create_table('UserCommission',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UCid', sa.String(length=64), nullable=False),
    sa.Column('OMid', sa.String(length=64), nullable=True),
    sa.Column('UCcommission', sa.DECIMAL(), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('UCstatus', sa.Integer(), nullable=True),
    sa.Column('UCcreateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('UCid')
    )
    op.create_table('UserLoginTime',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ULTid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('USTcreatetime', sa.DateTime(), nullable=True),
    sa.Column('USTip', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ULTid')
    )
    op.create_table('identifyingcode',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ICid', sa.String(length=64), nullable=False),
    sa.Column('ICtelphone', sa.String(length=14), nullable=False),
    sa.Column('ICcode', sa.String(length=8), nullable=False),
    sa.Column('ICtime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ICid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identifyingcode')
    op.drop_table('UserLoginTime')
    op.drop_table('UserCommission')
    op.drop_table('User')
    op.drop_table('AdminNotes')
    op.drop_table('Admin')
    # ### end Alembic commands ###
